### ISSUE TITLE
Choice to not insert a space after a tab completion

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#168] opened 2021-01-12 04:10 UTC
## What do you want?

A choice to not insert a space after a tab-completion.

## Why do you want this?

Sometimes, I want to rename a file or make a file with a similar name. For example, I want to run `mv test test.txt` so I do `mv test t<TAB>.txt`, but instead of `test.txt`, it ends up being `test .txt`. Rather than having zsh-autocomplete just insert the only choice (`test` is the only file in the current directory), I want to still use `<SPACE>` to confirm my selection. Since I usually press `<SPACE>` to confirm my completion, an extra space is often added which is also a bit annoying.

## Who else would benefit from this?

Anyone who prefers using `<SPACE>` to confirm their selection and work with lots of similar files?

## Explain in detail how you would expect this to work

Just don't insert a space after I press `<TAB>`.

**Comment by marlonrichert** [comment] 2021-01-12 09:21
How do you use <kbd>Space</kbd> to confirm your selection? Can you please give an example flow of events, so I can try it for myself?

**Comment by ChocolateOverflow** [comment] 2021-01-12 11:48
Currently, a space is automatically inserted when there's only possibly completion and I press `<TAB>`, making it `t<TAB>` -> `test ` (there's a space). There's no need to implement "press space to select", and instead just insert the completion without a space, making the sequence `t<TAB><SPACE>` give `test `.

If there're multiple possible completions (`test123` and `test456`), the sequence `t<TAB><SPACE>` would just give `test ` as the space exits the completion menu.

**Comment by marlonrichert** [comment] 2021-01-12 14:20
I think you misunderstood me. This is the part that I don't understand:

>  I want to still use `<SPACE>` to confirm my selection. Since I usually press `<SPACE>` to confirm my completion

**Comment by marlonrichert** [comment] 2021-01-12 14:20
> There's no need to implement "press space to select"

And what do you mean with that?

**Comment by ChocolateOverflow** [comment] 2021-01-13 02:46
Pressing `<SPACE>` would simply exit the completion menu. For example, with 2 files `asd123` and `asd456`, the sequence is as follows: `a<TAB>` -> `asd` (`asd123` and `asd456` suggested); `asd<SPACE>` -> `asd ` (exit the completion menu).

This is, I believe, the default behavior in bash. With zsh-autocomplete, a  space is automatically added after the completion, but I prefer to manually type in the space which also effectively exits the completion menu. It doesn't have to be a space either, inserting any character not key-bounded will simply insert that character and exit/update the completion menu.

**Comment by marlonrichert** [comment] 2021-01-15 21:58
I actually changed the code to _never_ add a space after completing. It seems to work pretty well. I'll add a setting to get the old behavior back if anyone asks for it.

PS: You might also want to add `setopt NO_autoparamslash` to your `.zshrc` file.

**Comment by ChocolateOverflow** [comment] 2021-01-16 09:23
I've pulled `c07bb2b` and added `setopt NO_autoparamslash` to my `.zshrc` but doing `vim t<TAB>` still expands to `vim test ` with a space when `test` is the only file in the currect directory. A space is still added, with or withour `.zshrc` and adding `setopt NO_autoparamslash` doesn't seem to get rid of the appended space either.

**Comment by marlonrichert** [comment] 2021-01-16 13:17
@ChocolateOverflow Sorry, but I cannot reproduce that. Here's what I did:
```zsh
> cd "$(mktemp -d)"  # Make & enter a temp dir.
> ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell without config files.
% source /Users/marlon/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% touch test
% vim te<tab>
% vim test
file
test
```
No space was added.

Do you perhaps have some other options or `zstyle` settings enabled that influence this?

**Comment by ChocolateOverflow** [comment] 2021-01-17 03:31
I've found that the option `zstyle ':autocomplete:tab:*' widget-style menu-select` was causing the space to be auto-appended. I'll try using zsh with the option off but it may be good to remove the extra space from that setting.

**Comment by marlonrichert** [comment] 2021-01-17 18:37
OK, that should be fixed now, too.

**Comment by ChocolateOverflow** [comment] 2021-02-03 01:53
After pulling `2c3c6dd37c81a2f33ac37b485645cb78ab6f6529`, setting `zstyle ':autocomplete:tab:*' widget-style menu-select` now auto-inserts a space upon `<TAB>` again.

**Comment by marlonrichert** [comment] 2021-02-03 06:20
@ChocolateOverflow It seems highly unlikely that 2c3c6dd37c81a2f33ac37b485645cb78ab6f6529 caused that. Can you please run `git bisect` to find out what is the actual commit that caused the regression?

**Comment by marlonrichert** [comment] 2021-02-03 21:00
@ChocolateOverflow I tried it out, but I cannot reproduce it. It might be that you have something cached on your system. Can you try deleting your compdump file and see if that helps?

**Comment by ChocolateOverflow** [comment] 2021-02-04 02:04
It seems to have been fixed after pulling `5924831`.

**Comment by marlonrichert** [comment] 2021-02-04 06:23
@ChocolateOverflow That’s pretty much impossible. Like I said, I think you’re having some caching problems. Try deleting your compdump file next time.

**Comment by marlonrichert** [comment] 2021-03-12 19:14
@ChocolateOverflow This is now implemented on the `main` branch. Please see the `add-space` setting in the Readme: https://github.com/marlonrichert/zsh-autocomplete/blob/main/README.md#settings

**Closed by marlonrichert** 2021-03-12 19:14 UTC
Labels: enhancement
