### ISSUE TITLE
Unexpected behavior for rupa/z

### ISSUE THREAD

**Issue by guiferpa** [marlonrichert/zsh-autocomplete#292] opened 2021-06-14 23:36 UTC
* `zsh-autocomplete` version: a1ee18e7d640dbf0ca2ae48001d7d35e9e7080cc
* Zsh version: ubuntu/5.8-3ubuntu1
* Framework: Oh My Zsh
* Plugin manager: "none"
* Operating system: linux-gnu

 ![image](https://user-images.githubusercontent.com/9096630/121971523-45ace000-cd4f-11eb-8abc-6f131d508ef4.png)
 
 I use [rupa/z](https://github.com/rupa/z) to jump around but when I just installed `zsh-autocomplete` I came across with this behavior that's not expected for me.
 
 I type the letter z + Space then the `zsh-autocomplete` show me this line: `zsh: do you wish to see all 54 possibilities (54 lines)?` .
 
 I already took a look on this issue https://github.com/marlonrichert/zsh-autocomplete/issues/5 but no solutions.

**Comment by marlonrichert** [comment] 2021-06-15 09:25
I'm unable to reproduce that. Can you share your `.z` file?

**Comment by guiferpa** [comment] 2021-06-15 22:09
**Command**: 
`cat z`

**Output**:
```
/home/guiferpa/Projects/src/github.com/pla-to|32|1623713970
/home/guiferpa/Projects/src/github.com/quartacasa|17|1621874240
/home/guiferpa/Projects/src/github.com/iupay/metrics-api|79|1621451983
/home/guiferpa/Projects/src/gitlab.gnome.org/GNOME|8|1621281574
/home/guiferpa/Projects/src/github.com/codito|2|1621016992
/home/guiferpa/Projects/src/github.com/codito/gnome-pomodoro|20|1621017572
/home/guiferpa/.asdf/plugins|2|1622327710
/home/guiferpa/Projects/src/github.com/pla-to/web-app/build/views/pages|2|1622512690
/home/guiferpa/Projects/src/github.com/iupay/traffic-ticket-api|132|1621892188
/home/guiferpa/.asdf/installs/golang/1.15/packages/pkg|2|1621451161
/home/guiferpa/Projects/src/github.com/iupay/metrics-api/dist/bin|2|1621450615
/home/guiferpa/Downloads/cmdline-tools/bin|5|1621874507
/home/guiferpa/Projects/src/github.com/quartacasa/balipark-interactive-map/dist|2|1621631655
/home/guiferpa/.asdf/plugins/flutter|2|1622327712
/home/guiferpa/Projects/src/github.com/pla-to/web-app/src/assets/images|3|1621296748
/home/guiferpa/Android|4|1621875246
/home/guiferpa/Android/Sdk|5|1623184320
/home/guiferpa/Downloads|37|1622175615
/home/guiferpa/Projects/src/github.com/pla-to/web-app/build/views|5|1622512691
/usr/local/android-studio/bin|5|1621874561
/home/guiferpa/Downloads/cmdline-tools|4|1621874511
/home/guiferpa/Projects|20|1623713948
/home/guiferpa/.asdf/installs/golang/1.15/packages/bin|7|1621451286
/|3|1621874642
/home/guiferpa/Projects/src/github.com/pla-to/api|114|1621022455
/home/guiferpa/.android|2|1621874543
/home/guiferpa/Projects/src/github.com/quartacasa/balipark-interactive-map/dist/assets-v2|3|1621637032
/home/guiferpa/.asdf/installs/golang/1.15|1|1621451172
/home/guiferpa/Android/Sdk/platform-tools|10|1623184319
/home/guiferpa/Projects/src/github.com/iupay/console-web|281|1623035407
/home/guiferpa/Projects/src/github.com/marlonrichert/zsh-autocomplete|18|1623712755
/home/guiferpa/.asdf/installs/golang|1|1621451174
/home/guiferpa/.asdf|2|1622327702
/home/guiferpa/Projects/src/github.com/pla-to/web-app/src/views|4|1621091686
/home/guiferpa/Projects/src/github.com/iupay/metrics-api/dist|3|1621450617
/home/guiferpa/Projects/src/github.com/iupay|55|1623712014
/home/guiferpa/Projects/src/github.com/pla-to/web-app/src/assets|7|1621528573
/home/guiferpa/Projects/src/github.com/quartacasa/genex-mobile|100|1623349829
/home/guiferpa/Projects/src/github.com/pla-to/web-app/build|2|1622512681
/home|2|1621868323
/home/guiferpa/.android/avd|2|1621874542
/home/guiferpa/Projects/src/gitlab.gnome.org|4|1621281024
/home/guiferpa/Projects/src/github.com/marlonrichert|11|1623712757
/usr/local/android-studio|8|1621874619
/home/guiferpa/Projects/src|24|1623713957
/home/guiferpa/Projects/src/github.com/pla-to/web-app/src|25|1621528574
/home/guiferpa/Projects/src/github.com|48|1623713967
/home/guiferpa/.asdf/installs/golang/1.15/packages|8|1621451274
/home/guiferpa/.asdf/plugins/flutter/bin|8|1622327799
/usr|5|1621874630
/usr/local|15|1621874626
/home/guiferpa/Projects/src/github.com/quartacasa/balipark-interactive-map|80|1621833718
/home/guiferpa/Projects/src/github.com/iupay/scripts|119|1622571155
/home/guiferpa/Projects/src/github.com/pla-to/web-app|648|1623783859

```

**Comment by marlonrichert** [comment] 2021-06-16 11:14
Ah, now I see why: It's because `rupa/z` generates completions using `compctl`, which is [the old, deprecated way to control completions](https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#The-zsh_002fcompctl-Module) in Zsh. Sorry, but `zsh-autocomplete` doesn't support that. You can try filing an issue with `rupa/z` to ask that they update their completions. Zsh "new" completion system was released in the year 2000; I don't think it's too much to ask that they start using it by now. 🙂

**Closed by marlonrichert** 2021-06-16 11:14 UTC
Labels: bug, question
