### ISSUE TITLE
Updating to `7b1a81c` or laters breaks `zsh-autocomplete` on M1 MacBookPro

### ISSUE THREAD

**Issue by mmhj** [marlonrichert/zsh-autocomplete#363] opened 2021-10-26 03:22 UTC
I'm running iTerm2 using zsh with omz on a 2020 M1 mbp.
I use the following plugins:

k
git-flow-completion
web-search
zsh-completions
zsh-autocomplete
zsh-autosuggestions
zsh-syntax-highlighting

After updating to 7b1a81c1673b1d78b849754c614247e9d509c27c the widget for autocomplete disappeared, and I instead see: 
```
missing `external command', `builtin command', `shell function', `alias', `reserved word', `suffix alias', `job', or `parameter'
```

### Environment
```
1e5e834e (HEAD -> master, origin/master, origin/HEAD) fix(cli): exit `omz update` with correct error code (#10342)
/Users/mhj/.zshrc:418
apple darwin20.0 /bin/zsh /bin/zsh zsh-5.8-0-g77d203f
```

### Steps to reproduce
I cannot reproduce the bug on a clean setup with no other plugins nor my normal .zshrc

**Comment by yrammos** [comment] 2021-10-29 21:52
Not knowing if this is related, I'm reporting nonetheless. I ran the diagnostic procedure of the GitHub issues template for this repo:

### Environment

```zsh
443544f (HEAD -> main, origin/main, origin/HEAD) Prevent syntax highlight from wrapping autosuggest
/Users/rammos/.zshrc:50
apple darwin21.0 /bin/zsh -zsh zsh-5.8-0-g77d203f
```

### Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1="%# " PS2="  "; setopt transientrprompt
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH FPATH=$FPATH TERM=$TERM zsh -d
```

Upon running the last command in the above sequence, i.e.

`env -i HOME=$PWD PATH=$PATH FPATH=$FPATH TERM=$TERM zsh -d`

I get the following result:

`.autocomplete.key-binding:92: terminfo[kpp]: parameter not set`

Typing works erratically past this point.

**Comment by marlonrichert** [comment] 2021-10-30 11:27
@yrammos Replace the last line with just `zsh -d` and try again.

**Comment by marlonrichert** [comment] 2021-10-30 11:28
@mmhj @yrammos Does this problem really occur only on M1 Macs? Have you tested it on other machines?

**Comment by yrammos** [comment] 2021-10-30 11:38
> @mmhj @yrammos Does this problem really occur only on M1 Macs? Have you tested it on other machines?

I haven't been, and sadly neither am I, able to test on other machines.

**Comment by yrammos** [comment] 2021-10-30 11:40
> @yrammos Replace the last line with just `zsh -d` and try again.

I did — confirming that the issue is reproduced.

**Comment by mmhj** [comment] 2021-10-30 11:48
> > I cannot reproduce the bug on a clean setup with no other plugins nor my normal .zshrc
> 
> Well, that doesn't help. Please try to put together a minimal test case with which I can reproduce the behavior that you think is incorrect. If I cannot reproduce it, then I cannot fix it.

Obviously, but that is what the bug reporting required, so I followed the steps exactly.

I have also tried to replace the last line with just `zsh -d` and the issue is reproduced.

I get the following result: 

`.autocomplete.key-binding:88: terminfo[kpp]: parameter not set`

**Comment by mmhj** [comment] 2021-10-30 11:49
> @mmhj @yrammos Does this problem really occur only on M1 Macs? Have you tested it on other machines?

I am not able to test on other machines. But I also tried to replace the last line with `zsh -d` and the issue is reproduced.

**Comment by mmhj** [comment] 2021-10-30 12:07
Not sure if this is related but reporting my findings anyway.

When I try to enter a directory by just typing the name of the dir I get the following error: 

```
No `external command', `builtin command', `shell function', `alias', `reserved word', `suffix alias', `job', or `parameter' matches found.
```

When I type `cd dir` I see the proper autocompletions i.e. the `directory` listings.

**Comment by marlonrichert** [comment] 2021-10-30 12:28
> When I try to enter a directory by just typing the name of the dir I get the following error

Aha, well, that's new information.

When you get this error, can you please run `setopt` and share the output here?

**Comment by mmhj** [comment] 2021-10-30 12:43
> > When I try to enter a directory by just typing the name of the dir I get the following error
> 
> Aha, well, that's new information.
> 
> When you get this error, can you please run `setopt` and `print $path[(r).]`, and share the output here?

`setopt`

```
alwaystoend
autocd
autonamedirs
autopushd
nobeep
cdablevars
combiningchars
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
interactive
interactivecomments
nolistbeep
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
```

`print $path[(r).]`

```
No `directory', `file', `ancestor directory', or `recent directory' matches found.`
```

Other than that autocomplete result I get no output from `print $path[(r).]`

**Comment by marlonrichert** [comment] 2021-10-31 09:15
I'm able to reproduce it now and should have a fix soon.

**Comment by marlonrichert** [comment] 2021-10-31 17:22
Should be fixed now. Let me know if you still experience problems.

**Closed by marlonrichert** 2021-10-31 17:22 UTC
Labels: bug

**Comment by yrammos** [comment] 2021-10-31 18:35
@marlonrichert unfortunately the plugin is still broken on my end. This might be the sign of a different problem: I reacted to this thread because the first breaking commit is the one mentioned in the OP's title (`7b1a81c`)—that is to say, the last working commit is `ec9de3c`— and I likewise have an m1 MBP. My symptomatology however is slightly different: I don't see the message mentioned by the OP in the original post. Rather, the plugin silently fails tp autocomplete. As soon as I `git checkout` the aforementioned last-working commit, and reload, things go back to normal. I should have probably opened a separate issue and could do so at this stage, if you prefer.

**Comment by mmhj** [comment] 2021-10-31 18:52
Just confirming that on my end everything seems to be working now.

I can autocd, the directories show up, I get none of the messages I've previously mentioned, so far at least, I will continue testing tomorrow.

@yrammos Let me know if I can help troubleshoot, since we have a similar setup.

**Comment by marlonrichert** [comment] 2021-10-31 18:53
@yrammos Yes, please open a new issue for this.
