### ISSUE TITLE
Windows does not allow you to have a '?' in a filename, just like it does not allow to have a "\" or "*".

### ISSUE THREAD

**Issue by ashari0831** [marlonrichert/zsh-autocomplete#636] opened 2023-08-22 09:40 UTC
Please remove any of these characters from file names. As a result, we will be able to use it in git bash windows.

The problem is when I clone it, these errors happened:

***
error: unable to create file Functions/Widgets/.autocomplete:complete-word:completion-widget: Invalid argument
error: unable to create file Functions/Widgets/.autocomplete:complete-word:post: Invalid argument
error: unable to create file Functions/Widgets/.autocomplete:down-line-or-select:zle-widget: Invalid argument
error: unable to create file Functions/Widgets/.autocomplete:history-search:completion-widget: Invalid argument
error: unable to create file Functions/Widgets/.autocomplete:up-line-or-search:zle-widget: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
***

**Comment by marlonrichert** [comment] 2023-08-22 09:42
Duplicate of #623.

**Closed by marlonrichert** 2023-08-22 09:42 UTC
Labels: bug
