### ISSUE TITLE
zsh-autocomplete creates huge logs (upto size 400 GBs)

### ISSUE THREAD

**Issue by ShrirajHegde** [marlonrichert/zsh-autocomplete#399] opened 2022-01-13 20:26 UTC
### Environment

```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```
OUTPUT:
- redhat linux-gnu /usr/bin/zsh /usr/bin/zsh zsh-5.8-0-g77d203f
- <empty>
-  4fd8a6c (HEAD -> main, origin/main, origin/HEAD) Fix link to `.autocomplete.config` in Readme

### Steps to reproduce
It happens eventually over time. So I am not sure of reproducing. 
![image](https://user-images.githubusercontent.com/66936172/149403233-82b308ac-cfb3-485f-ac34-50c93e58f479.png)
![image](https://user-images.githubusercontent.com/66936172/149403244-98f569de-2293-43bb-9b62-c81cbe11c97a.png)

Size increase just in 2-3 minutes.
![image](https://user-images.githubusercontent.com/66936172/149403374-3ad2a4a3-a4a5-44a3-8246-1fe25d6e1090.png)

Content inside large log file:
```
.autocomplete.recent_paths.trim:shift:3: shift count must be <= $#
.autocomplete.recent_paths.trim:shift:3: shift count must be <= $#
.autocomplete.recent_paths.trim:shift:3: shift count must be <= $#
```
This on repeat.

zsh process writing the log file:
![image](https://user-images.githubusercontent.com/66936172/149403578-f76dd462-2cd6-4be4-9563-8283b537d2a8.png)

This process does not respond to SIGTERM and requires SIGKILL.

Is there any way to disable logging as a temporary fix?

**Comment by marlonrichert** [comment] 2022-01-14 14:04
Please do the following:
* Share a copy of the file `~/.local/share/zsh/chpwd-recent-dirs`
* Post the value of `$COLUMNS` for which the problem occurs.
* Run `functions -T .autocomplete.recent_paths.trim` and share the log contents generated after that.

**Comment by ShrirajHegde** [comment] 2022-01-16 05:15
- >Share a copy of the file ~/.local/share/zsh/chpwd-recent-dirs

```
$'/home/srj/Desktop/misc/installers/distro-grub-themes/customize'
$'/home/srj/Desktop/misc/installers'
$'/media/srj/storage/Others/temp/test'
$'/home/srj
```
- >Post the value of $COLUMNS for which the problem occurs.

80 (80x24 default size)

- >Run functions -T .autocomplete.recent_paths.trim and share the log contents generated after that.

Empty with non-zero exit code.

![image](https://user-images.githubusercontent.com/66936172/149647997-e2c92c7d-426c-41fb-a82f-f4bf13c4b4d4.png)

**Comment by marlonrichert** [comment] 2022-01-17 12:32
> - >Run functions -T .autocomplete.recent_paths.trim and share the log contents generated after that.
> 
> Empty with non-zero exit code.

Those are not the contents of the log. Again, run `functions -T .autocomplete.recent_paths.trim`, then share what is printed _in the log_ after doing so.

**Comment by marlonrichert** [comment] 2022-01-17 12:34
> ```
> $'/home/srj/Desktop/misc/installers/distro-grub-themes/customize'
> $'/home/srj/Desktop/misc/installers'
> $'/media/srj/storage/Others/temp/test'
> $'/home/srj
> ```
> 

Are you sure that's the _entire_ contents of `~/.local/share/zsh/chpwd-recent-dirs`? It should end in a `'`.

**Comment by ShrirajHegde** [comment] 2022-01-17 15:07
>Are you sure that's the entire contents of ~/.local/share/zsh/chpwd-recent-dirs? It should end in a '.

It does, I missed it while copying.

**Comment by marlonrichert** [comment] 2022-01-18 14:46
> > - >Run functions -T .autocomplete.recent_paths.trim and share the log contents generated after that.
> > 
> > Empty with non-zero exit code.
> 
> Those are not the contents of the log. Again, run `functions -T .autocomplete.recent_paths.trim`, then share what is printed _in the log_ after doing so.

@ShrirajHegde And what about this? ☝🏽

**Comment by ShrirajHegde** [comment] 2022-01-18 15:01
> @ShrirajHegde And what about this?

Sorry, somehow missed that.


 here it is


```


# 15. .autocomplete.recent_paths.trim [20:30:08.046]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.547]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.572]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.586]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.619]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.649]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.676]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.706]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))

# 15. .autocomplete.recent_paths.trim [20:30:08.953]
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
49	local -P total='/  '
50	while ((  3 > COLUMNS  ))
```

**Comment by ShrirajHegde** [comment] 2022-01-23 14:35
@marlonrichert is there a way to disable logging for temporary resolution??

It is filling up my file system

![image](https://user-images.githubusercontent.com/66936172/150683627-ded61987-d242-47bb-b9ba-6aa46aa0f8bc.png)

**Comment by marlonrichert** [comment] 2022-01-24 11:56
Add this to your `.zshrc` file, _after_ sourcing Zsh Autcomplete:
```zsh
.autocomplete.recent_paths.trim() {:}
```

**Comment by marlonrichert** [comment] 2022-04-20 13:33
Closing, as I'm unable to reproduce it.

**Closed by marlonrichert** 2022-04-20 13:33 UTC
Labels: invalid
