### ISSUE TITLE
command not found: .autocomplete.key

### ISSUE THREAD

**Issue by BeforeFlight** [marlonrichert/zsh-autocomplete#187] opened 2021-02-14 09:23 UTC
* `zsh-autocomplete` version: `c4dea766566b168a32dbfa8d10335e525ce39fcc`
* Zsh version: ubuntu/5.8-5
* Framework: Oh My Zsh
* Plugin manager: zplug

After this commit: `6529dfa49bdc1cc0098ec4bfa16b0d5497a93d25` (Refactor `precmd` hooks)
Just on loading zsh getting this:
```
.autocomplete.key-binding.precmd:2: command not found: .autocomplete.key
"complete-word" undefined-key
"complete-word" undefined-key
```

**Comment by marlonrichert** [comment] 2021-02-14 12:13
I am unable to reproduce this.

Do you get this, too, when you do the following?
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
```
If not, then
* A) there is something else in your `.zshrc` file that's interfering or
* B) there is a caching problem.
The latter can be fixed by deleting `$_comp_dumpfile`.

**Comment by BeforeFlight** [comment] 2021-02-14 21:11
I've reduced the `.zshrc` to minimum, and also tried to remove `$_comp_dumpfile`, as suggested.
Same error if use `zplug` manager but if clone/source `zsh-autocomplete` manually - no errors.

#### So it happens to be following inconsistency:
* Installation of your plugin requres `3) Remove any calls to compinit from your ~/.zshrc file`
* But at the same time zplug runs ``compinit`` on its loading (it can be shown when load it with `zplug load --verbose` option in .zshrc)

But it seems to work fine (at first sight) when sourcing `zsh-autocomplete` manually (before `source ~/.zplug/init.zsh`), while left other plugins managed by `zplug`. So switched to this for now.

**Comment by BeforeFlight** [comment] 2021-02-14 21:12
But it seems to work fine (at first sight) when sourcing `zsh-autocomplete` manually (before `source ~/.zplug/init.zsh`), while left other plugins managed by `zplug`. So switched to this for now.

**Comment by marlonrichert** [comment] 2021-02-18 20:52
Fixed.

**Comment by BeforeFlight** [comment] 2021-02-18 21:04
Confirm. No previous errors shown.

**Comment by flexagoon** [comment] 2021-06-07 03:00
It happened to me. I am also using Zinit plugin manager, but my error text is slightly longer:

```
.autocomplete.key-binding.precmd:3: .autocomplete.key: function definition file not found
"complete-word" undefined-key
"complete-word" undefined-key
"complete-word" undefined-key
"complete-word" undefined-key
"accept-line" undefined-key
"send-break" undefined-key
```

**Comment by marlonrichert** [comment] 2021-06-07 07:39
This appears to be a regression introduced by 68bae9522a53fdffcc93be0453daf71b09175ef9.

**Comment by marlonrichert** [comment] 2021-06-07 20:43
Should be fixed now.

**Closed by marlonrichert** 2021-06-07 20:43 UTC
Labels: bug

**Comment by flexagoon** [comment] 2021-06-08 05:40
Doesn't help. Here's my .zsh config:
https://dpaste.com/5ETLF2F3X

**Comment by flexagoon** [comment] 2021-06-08 05:44
Oh wait, nvm, I just forgot to run `zplug update`. Thanks!

**Comment by marlonrichert** [comment] 2021-06-08 06:42
If you use my software on a regular basis, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
