### ISSUE TITLE
man: do you wish to see X possibilities

### ISSUE THREAD

**Issue by Omoeba** [marlonrichert/zsh-autocomplete#396] opened 2022-01-09 23:27 UTC
### Environment

```zsh
apple darwin21.0 zsh zsh-5.8-0-g77d203f

06b887a (grafted, HEAD -> main, origin/main, origin/HEAD) Fix quoting bug in history completion
```

### Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- Type `man` followed by a space
```
% man 
zsh: do you wish to see all 1773 possibilities (357 lines)?
```

**Comment by marlonrichert** [comment] 2022-01-11 15:37
Duplicate of #388.

**Closed by marlonrichert** 2022-01-11 15:37 UTC
Labels: duplicate
