### ISSUE TITLE
Random freeze?

### ISSUE THREAD

**Issue by tmpm697** [marlonrichert/zsh-autocomplete#56] opened 2020-06-11 20:25 UTC
### Describe the bug
When I use this plugin it freeze the whole pc, force to hard reboot.

### To Reproduce

```sh
vi .zshrc
source zsh-autocomplete/zsh-autocomplete.zsh
source zsh-histdb/sqlite-history.zsh
```

play around with this plugin especially with tab, and it gives random freeze then bring down the pc to unresponsive behavior, then force hard reboot.

### Expected behavior
It should not freeze the pc.

### Desktop
 - OS + distribution:   Archlinux up-to-date
 - Zsh version:  5.8
- tmux: next-3.2

**Comment by marlonrichert** [comment] 2020-06-12 09:56
Here's what I did to reproduce it:
```shell
% cd "$(mktemp -d)"
% ZDOTDIR=$PWD HOME=$PWD zsh -df
% source path/to/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source path/to/larkery/zsh-histdb/sqlite-history.zsh
autoload -Uz add-zsh-hook
add-zsh-hook precmd histdb-update-outcome
```
Works fine for me. 0.1% CPU usage.

I think you might have something else going on that's interfering?

**Comment by tmpm697** [comment] 2020-06-15 02:41
I re-try but still the same result, Idk what would cause this issue. it seems your above setup run without issue if I spin up a another new user -- but because I `su -l <user>` so it does not come with X-org or terminal ..etc.

I use .zshenv and .zshrc but this time to test, I disabled .zshenv -- only specify ZDOTDIR in it. 

So does this issue come from terminal/x-org or something graphical related components?

**Comment by marlonrichert** [comment] 2020-06-15 07:41
I have no idea.

You could try running `top` and keep it visible while you reproduce this, to see where your CPU usage goes.

**Comment by marlonrichert** [comment] 2020-06-15 07:42
> play around with this plugin especially with tab

How do you "play around" with it? Can you find specific set of cases for which it freezes?

**Comment by tmpm697** [comment] 2020-06-16 06:55
I `play around` by just spam keys and make it heavy use like press `ls` and -l` then hold tab to have all options listed ..etc.

This happens with just `st` terminal and `tmux` also.

**Comment by marlonrichert** [comment] 2020-06-16 07:32
> press `ls` and -l` then hold tab to have all options listed ..etc.

First of all, when using `zsh-autocomplete`, pressing Tab does not list completions. Completions are listed automatically. Pressing Tab will just insert the completion that's at the top of the list. If it doesn't work that way for you, then you have `zsh-autocomplete` incorrectly installed somehow.

Secondly, I can write `ls -l`, then press Tab a hundred times and it works fine.

Please try to come up with step-by-step instructions with which this can be reproduced. Until then, I'm going to close this, because it does not appear there's anything I can do about it.

**Closed by marlonrichert** 2020-06-16 07:32 UTC
Labels: Bug report
