### ISSUE TITLE
Breaks `copy-earlier-word`

### ISSUE THREAD

**Issue by unphased** [marlonrichert/zsh-autocomplete#425] opened 2022-03-27 07:55 UTC
## Environment

```zsh
apple darwin21.0 /bin/zsh -zsh zsh-5.8-0-g77d203f
/Users/slu/Git/zsh-snap/functions/.znap.source:26
/Users/slu/Git/zsh-snap/functions/znap:42
/Users/slu/.zshrc:112
```
* Operating system: macOS, Ubuntu
* Terminal emulator: alacritty

## Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

Results: 

```
❯ cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 0), reused 25 (delta 0), pack-reused 0
Receiving objects: 100% (59/59), 1.64 MiB | 8.35 MiB/s, done.
% echo abc def ghi
abc def ghi
% autoload -Uz copy-earlier-word
zle -N copy-earlier-word
bindkey "\e," copy-earlier-word

% echo typing alt+, here does not let me hop from "ghi" to "def"!
typing alt+, here does not let me hop from ghi to def!
%
```

Here is what happens when i remove the sourcing of the repo in that vim command seen below and then run the clean zsh:
```
🔋83% at 03:53:32 ❯ vim .zshrc
cnhyxq8n21ngdq0xmw5l_t3m0000gn/T/tmp.Qe37rrvi took 2s
🔋83% at 03:53:38 ❯ env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% autoload -Uz copy-earlier-word
zle -N copy-earlier-word
bindkey "\e," copy-earlier-word

% echo abc def ghi
abc def ghi
% def
zsh: command not found: def
% echo it works here
it works here
%
```

**Comment by marlonrichert** [comment] 2022-03-31 13:41
That's currently impossible to fix inside Zsh Autocomplete. The problem is that it relies on ZLE hooks that need to be implemented with widgets. As a result, the value of `$LASTWIDGET` changes.

https://github.com/zsh-users/zsh/commit/0cffb0a6b3602a00cebe2bbb7537d76727892959 implements a way to invoke ZLE widgets without changing `$LASTWIDGET`, but there is as of yet no Zsh release yet that contains this commit. [Hopefully we'll see Zsh 5.9 released soon](https://www.zsh.org/mla/workers/2022/msg00259.html).

**Comment by unphased** [comment] 2022-04-01 04:48
Thank you. As I understand it now, once 5.9 makes the new approach available to implement ZLE widgets without clobbering `$LASTWIDGET`, we could switch implementation to this, and it would enable `copy-earlier-word` and any other broken stuff that has the same root cause to all work again.

**Comment by marlonrichert** [comment] 2022-04-01 10:23
Yes, that is correct and I intend to make that change, once it's possible.

**Comment by marlonrichert** [comment] 2022-08-17 07:11
OK, Zsh 5.9 has been released and that commit is in it. However, Zsh Autocomplete relies [here](https://github.com/marlonrichert/zsh-autocomplete/blob/4decd760641377e818d11146ef1249f5474c224a/scripts/.autocomplete.async#L153) on the value of `$LASTWIDGET` to avoid a crash when autocompletion causes the line to be redrawn. I'll have to test if this still an issue in Zsh 5.9 and, if so, I'll have to come up with another workaround.

**Comment by marlonrichert** [comment] 2022-09-27 13:21
I haven't had the time to look into this. Help in the form of a pull request would be appreciated. 🙂

**Comment by marlonrichert** [comment] 2022-11-16 15:09
@unphased I investigated it and it turns out it's actually a bug in the Zsh Line Editor. I filed a bug report about it to the Zsh development group: https://www.zsh.org/mla/workers/2022/msg01311.html

Closing this issue as there is no workaround possible for this.

**Closed by marlonrichert** 2022-11-16 15:09 UTC
Labels: bug
