### ISSUE TITLE
[Duplicate] Not working after updating -  zsh: :autocomplete:old:_main_complete: command not found...

### ISSUE THREAD

**Issue by lime-desu** [marlonrichert/zsh-autocomplete#541] opened 2023-02-05 00:50 UTC
- [x] I have carefully read all the instructions in this issue template.
- [x] I have carried them out to the letter.

Did a full update on my system after updating zsh-autocomplete broke on the latest commit, pressing tab will show 
`zsh: :autocomplete:old:_main_complete: command not found...`

## Environment
```zsh
❯ print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
redhat linux-gnu /usr/bin/zsh -zsh zsh-5.9-0-g73d3173
/home/void/.config/zsh/.zshrc:111
80a89b9 (HEAD -> main, origin/main, origin/HEAD) Remove VS Code settings
```

* Operating system:  Fedora Linux
* Terminal emulator:  Alacritty

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 57 (delta 0), reused 29 (delta 0), pack-reused 0
Receiving objects: 100% (57/57), 1.64 MiB | 1.81 MiB/s, done.
% lautocomplete:new:_main_complete:14: command not found: :autocomplete:old:_main_complete
ls
zsh-autocomplete
% autocomplete:new:_main_complete:14: command not found: :autocomplete:old:_main_complete
autocomplete:new:_main_complete:14: command not found: :autocomplete:old:_main_complete

```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by polyzen** [comment] 2023-02-05 01:24
Duplicate of #540

**Closed** 2023-02-05 04:10 UTC
Labels: bug
