### ISSUE TITLE
macOS has issues with zsh-autocomplete

### ISSUE THREAD

**Issue by Dragonizedpizza** [marlonrichert/zsh-autocomplete#578] opened 2023-04-19 17:53 UTC
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

```
.autocomplete.async.complete.fd-widget:3: not a directory: /Users/arch/.local/state/zsh-autocomplete/log/2023-04-19.log
```

## Environment
```zsh
typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

![image](https://user-images.githubusercontent.com/70718540/233158527-ea8f8340-941f-4325-8e36-ca1e90c911cf.png)
(I have had to disable zsh-autocomplete, I am spammed with the error above which makes it unusable)

* Operating system:  macOS
* Terminal emulator:  iTerm2

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block.

## Steps to reproduce
zsh on macOS with this [.zshrc](https://pastebin.com/dNGEjbtZ)

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by Bens0** [comment] 2023-04-19 18:03
I have the same issue

**Comment by killertofus** [comment] 2023-04-19 22:42
same on arch 6.2

**Comment by ChiefMateStarbuck** [comment] 2023-04-20 15:36
+1

**Comment by mattorp** [comment] 2023-04-21 10:05
This solved it for me (replace `repos/` with the path you use for repos)

```bash
cd repos
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
```

And in `~/.zshrc` remove `znap source zsh-autocomplete/zsh-autocomplete` if using znap. Then add this to `~/.zshrc`

```txt
source ~/repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```

**Comment by edeetee** [comment] 2023-04-24 03:21
I fixed this by deleting the .local/state/zsh-autocomplete file.  I tried to install this without znap properly installed first which may have had something to do with it.

**Comment by marlonrichert** [comment] 2023-05-01 19:37
Duplicate of #571.

**Closed by marlonrichert** 2023-05-01 19:37 UTC
Labels: bug
