### ISSUE TITLE
Mismatched history due to history picked from $HISTFILE

### ISSUE THREAD

**Issue by ShrirajHegde** [marlonrichert/zsh-autocomplete#165] opened 2021-01-10 16:14 UTC
## Environment
* `zsh-autocomplete` version: 1f59fc6ec81a589dd744800fc5d92d371da5fc09
* Zsh version: zsh-5.8-0-g77d203f 
* Framework: none 
* Plugin manager: none 
* `~/.zshrc` file: https://pastebin.com/6E0pP4MJ 

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* Not sure

If not, gradually add lines from your config file to the subshell until the bug appears.

## Steps to reproduce

1. Vanilla zsh with p10k theme,zsh-syntaxhighting,zsh-autosuggestions,zsh-autocomplete

### Actual behavior
Wrong history gets selected and executed

### Expected behavior
Right history gets selected and executed 

![Screenshot from 2021-01-10 21-14-34](https://user-images.githubusercontent.com/66936172/104127984-0e469b80-538b-11eb-8b4e-e5a157e7e0b7.png)
![Screenshot from 2021-01-10 21-14-36](https://user-images.githubusercontent.com/66936172/104127995-1999c700-538b-11eb-967e-20ba60e571a6.png)
![Screenshot from 2021-01-10 21-14-39](https://user-images.githubusercontent.com/66936172/104128008-2a4a3d00-538b-11eb-8c0b-01efe021392c.png)
![Screenshot from 2021-01-10 21-14-42](https://user-images.githubusercontent.com/66936172/104128014-3209e180-538b-11eb-931a-17828844a126.png)

**Comment by marlonrichert** [comment] 2021-01-10 18:18
Sorry, but I cannot reproduce this. Can you please test without config files and tell me if the bug happens then? Like this:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```

**Comment by ShrirajHegde** [comment] 2021-01-10 19:01
yes, the problem is persistant 


![image](https://user-images.githubusercontent.com/66936172/104132537-f4658280-53a3-11eb-8294-4791fce82b3d.png)


This problem happens since zsh doesn't write history entries until exit. (probably to isolate instances).

**Comment by marlonrichert** [comment] 2021-01-10 19:14
Sorry, but I still cannot reproduce this:
<img width="682" alt="Screen Shot 2021-01-10 at 21 12 11" src="https://user-images.githubusercontent.com/644725/104132875-adb65f00-5388-11eb-861d-b951fe947b19.png">

I just noticed you are not using the latest version of `zsh-autocomplete`, though. Can you please update and tell me if it still happens for you?

**Comment by marlonrichert** [comment] 2021-01-10 19:23
If the update doesn't help, can you please try the following?
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Press ↑, then ^C.
% functions -T _autocomplete.history_lines
% # Press ↑ again.
```
Then please copy-paste the debug output here.

**Comment by ShrirajHegde** [comment] 2021-01-11 10:56
Ok, figured it out, there's a lot of conflict with zsh autocomplete. Disabling zsh autocomplete makes zsh write history to $HISTFILE immediately after command execution which fixes the issue

I am not 100% sure since yesterday the problem happened.

**Comment by marlonrichert** [comment] 2021-01-11 10:59
This has nothing to do with the `$HISTFILE`. Can you please try these debug steps that I asked you to do?

> ```zsh
> $ cd $(mktemp -d)  # Create a temp dir and enter it.
> $ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
> % source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
> % # Press ↑, then ^C.
> % functions -T _autocomplete.history_lines
> % # Press ↑ again.
> ```
> Then please copy-paste the debug output here.

**Comment by ShrirajHegde** [comment] 2021-01-11 14:04
```
srj% functions -T _autocomplete.history_lines
srj% +_autocomplete.history_lines:1> local tag=history-lines
+_autocomplete.history_lines:2> _tags history-lines
+_autocomplete.history_lines:3> _tags
+_autocomplete.history_lines:3> _requested history-lines
+_autocomplete.history_lines:6> local -aU events=( )
+_autocomplete.history_lines:7> local -i max_lines=3
+_autocomplete.history_lines:8> [[ -z '' ]]
+_autocomplete.history_lines:9> local query='<-16>'
+_autocomplete.history_lines:9> [[ history-search:autocomplete.history-lines:: == *-forward:* ]]
+_autocomplete.history_lines:10> query='<0->' 
+_autocomplete.history_lines:11> print -v events -f '%1.1s  %s' 2 'functions -T _autocomplete.history_lines' 1 'source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh'
+_autocomplete.history_lines:12> [[ history-search:autocomplete.history-lines:: == *-incremental-*-forward:* ]]
+_autocomplete.history_lines:47> local -a sopt=( -S '' )
+_autocomplete.history_lines:48> [[ history-search:autocomplete.history-lines:: = history-search:* ]]
+_autocomplete.history_lines:49> events=( '1  source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh' '2  functions -T _autocomplete.history_lines' ) 
+_autocomplete.history_lines:50> sopt=( -S ';' -R _autocomplete.history_lines.suffix ) 
+_autocomplete.history_lines:53> local MATCH
+_autocomplete.history_lines:53> local -i MBEGIN MEND
+_autocomplete.history_lines:54> local -a displays=( '1  source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh           ' '2  functions -T _autocomplete.history_lines                                    ' )
+_autocomplete.history_lines:58> events=( 'source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh' 'functions -T _autocomplete.history_lines' ) 
+_autocomplete.history_lines:59> [[ history-search:autocomplete.history-lines:: == *-incremental-* ]]
+_autocomplete.history_lines:62> local _comp_no_ignore=1 expl
+_autocomplete.history_lines:63> _description -2V history-lines expl 'history line'
+_autocomplete.history_lines:64> compadd -2 -o nosort -J history-lines -QU -S ';' -R _autocomplete.history_lines.suffix -ld displays -a events
functfunctions -T _autocomplete.history_lines;

```

**Comment by ShrirajHegde** [comment] 2021-01-11 14:06
> This has nothing to do with the `$HISTFILE`, as far as I can tell. Can you please try these debug steps that I asked you to do?
> 
> > ```shell
> > $ cd $(mktemp -d)  # Create a temp dir and enter it.
> > $ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
> > % source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
> > % # Press ↑, then ^C.
> > % functions -T _autocomplete.history_lines
> > % # Press ↑ again.
> > ```
> > 
> > 
> > Then please copy-paste the debug output here.

I this it has something to do with it. I have checked file being modified in realtime. with zsh-autosuggestions $HISTFILE is written only when user exits terminal

**Comment by marlonrichert** [comment] 2021-01-11 14:47
> ```
> srj% functions -T _autocomplete.history_lines
> srj% +_autocomplete.history_lines:1> local tag=history-lines
> +_autocomplete.history_lines:2> _tags history-lines
> +_autocomplete.history_lines:3> _tags
> +_autocomplete.history_lines:3> _requested history-lines
> +_autocomplete.history_lines:6> local -aU events=( )
> +_autocomplete.history_lines:7> local -i max_lines=3
> +_autocomplete.history_lines:8> [[ -z '' ]]
> +_autocomplete.history_lines:9> local query='<-16>'
> +_autocomplete.history_lines:9> [[ history-search:autocomplete.history-lines:: == *-forward:* ]]
> +_autocomplete.history_lines:10> query='<0->' 
> +_autocomplete.history_lines:11> print -v events -f '%1.1s  %s' 2 'functions -T _autocomplete.history_lines' 1 'source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh'
> +_autocomplete.history_lines:12> [[ history-search:autocomplete.history-lines:: == *-incremental-*-forward:* ]]
> +_autocomplete.history_lines:47> local -a sopt=( -S '' )
> +_autocomplete.history_lines:48> [[ history-search:autocomplete.history-lines:: = history-search:* ]]
> +_autocomplete.history_lines:49> events=( '1  source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh' '2  functions -T _autocomplete.history_lines' ) 
> +_autocomplete.history_lines:50> sopt=( -S ';' -R _autocomplete.history_lines.suffix ) 
> +_autocomplete.history_lines:53> local MATCH
> +_autocomplete.history_lines:53> local -i MBEGIN MEND
> +_autocomplete.history_lines:54> local -a displays=( '1  source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh           ' '2  functions -T _autocomplete.history_lines                                    ' )
> +_autocomplete.history_lines:58> events=( 'source /home/shriraj/zsh-autocomplete/zsh-autocomplete.plugin.zsh' 'functions -T _autocomplete.history_lines' ) 
> +_autocomplete.history_lines:59> [[ history-search:autocomplete.history-lines:: == *-incremental-* ]]
> +_autocomplete.history_lines:62> local _comp_no_ignore=1 expl
> +_autocomplete.history_lines:63> _description -2V history-lines expl 'history line'
> +_autocomplete.history_lines:64> compadd -2 -o nosort -J history-lines -QU -S ';' -R _autocomplete.history_lines.suffix -ld displays -a events
> functfunctions -T _autocomplete.history_lines;
> 
> ```

@ShrirajHegde Did the bug occur when you did this? This output looks completely correct to me.

**Comment by ShrirajHegde** [comment] 2021-01-11 14:49
No bug doesn't occur when zsh-autosuggestions isn't being used.

**Comment by marlonrichert** [comment] 2021-01-11 14:49
@ShrirajHegde That was not my question.

**Comment by ShrirajHegde** [comment] 2021-01-11 14:50
> Ok, figured it out, there's a lot of conflict with zsh autocomplete. Disabling zsh autocomplete makes zsh write history to $HISTFILE immediately after command execution which fixes the issue
> 
> I am not 100% sure since yesterday the problem happened.

Ok I miswrote here, I meant **zsh-autosuggestions** not autocomplete

**Comment by ShrirajHegde** [comment] 2021-01-11 14:54
can you please add somewhere that this isn't compatible along with zsh-autosuggestions??

**Comment by ShrirajHegde** [comment] 2021-01-11 14:55
adding support is kind of pointless since zsh-autosuggestions and these have similar functionality.

**Comment by marlonrichert** [comment] 2021-01-11 19:19
Sorry, but I cannot reproduce your problem. I use both `zsh-autocomplete` and `zsh-autosuggestions` at the same time and it works fine. If you can please use the debug template I gave you to put together a test case that can reproduce the problem, then I can investigate the problem.

**Comment by ShrirajHegde** [comment] 2021-01-12 06:05
> Sorry, but I cannot reproduce your problem. I use both `zsh-autocomplete` and `zsh-autosuggestions` at the same time and it works fine. If you can please use the debug template I gave you to put together a test case that can reproduce the problem, then I can investigate the problem.

oh ok, can you provide your zshrc??

**Comment by marlonrichert** [comment] 2021-01-12 09:27
https://github.com/marlonrichert/.config/blob/master/zsh/.zshrc

**Comment by seboudry** [comment] 2021-01-14 17:35
Hi !

I've same bugged behaviour since update on current version.
Doesn't have updated this plugin since a few months, so I can't give a tip from when this behaviour changed.

I have test piece of code from [this comment](https://github.com/marlonrichert/zsh-autocomplete/issues/165#issuecomment-757529508), and here's my observations.

With an existing history.
I want item `6988 docker ps -a` but following item `6989  cd dev` is selected, bogus from this item to last item.
Previous items (five first items) are selected as wanted.
It seems that item `6988` is present in shown list but not in underlying list.

```
cd $(mktemp -d)
cp /home/me/.zsh_history .
ZDOTDIR=$PWD HOME=$PWD zsh -f
MY-LAPTOP% fc -p $PWD/.zsh_history
MY-LAPTOP% source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
MY-LAPTOP% functions -T _autocomplete.history_lines
MY-LAPTOP% +_autocomplete.history_lines:1> local tag=history-lines
+_autocomplete.history_lines:2> _tags history-lines
+_autocomplete.history_lines:3> _tags
+_autocomplete.history_lines:3> _requested history-lines
+_autocomplete.history_lines:6> local -aU events=( )
+_autocomplete.history_lines:7> local -i max_lines=16
+_autocomplete.history_lines:8> [[ -z '' ]]
+_autocomplete.history_lines:9> local query='<-16>'
+_autocomplete.history_lines:9> [[ history-search:autocomplete.history-lines:: == *-forward:* ]]
+_autocomplete.history_lines:10> query='<6983->' 
+_autocomplete.history_lines:11> print -v events -f '%4.4s  %s' 6998 'functions -T _autocomplete.history_lines' 6997 'source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh' 6996 'cp /home/me/.zsh_history .' 6995 'cd $(mktemp -d)' 6994 'ZDOTDIR=$PWD HOME=$PWD zsh -f' 6993 'cd $(mktemp -d)' 6992 'ZDOTDIR=$PWD HOME=$PWD zsh -f' 6991 'cd $(mktemp -d)' 6990 'atom .' 6989 'cd dev' 6988 'docker ps -a' 6987 'docker system prune' 6986 'docker ps -a' 6985 'ps -aux | grep -v grep | grep worker' 6984 'ps -aux | grep -v grep | grep zbctl' 6983 'ps -aux | grep -v grep | grep zbctl | awk ''{print $2}'' | xargs kill'
+_autocomplete.history_lines:12> [[ history-search:autocomplete.history-lines:: == *-incremental-*-forward:* ]]
+_autocomplete.history_lines:47> local -a sopt=( -S '' )
+_autocomplete.history_lines:48> [[ history-search:autocomplete.history-lines:: = history-search:* ]]
+_autocomplete.history_lines:49> events=( '6983  ps -aux | grep -v grep | grep zbctl | awk ''{print $2}'' | xargs kill' '6984  ps -aux | grep -v grep | grep zbctl' '6985  ps -aux | grep -v grep | grep worker' '6986  docker ps -a' '6987  docker system prune' '6988  docker ps -a' '6989  cd dev' '6990  atom .' '6991  cd $(mktemp -d)' '6992  ZDOTDIR=$PWD HOME=$PWD zsh -f' '6993  cd $(mktemp -d)' '6994  ZDOTDIR=$PWD HOME=$PWD zsh -f' '6995  cd $(mktemp -d)' '6996  cp /home/me/.zsh_history .' '6997  source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh' '6998  functions -T _autocomplete.history_lines' ) 
+_autocomplete.history_lines:50> sopt=( -S ';' -R _autocomplete.history_lines.suffix ) 
+_autocomplete.history_lines:53> local MATCH
+_autocomplete.history_lines:53> local -i MBEGIN MEND
+_autocomplete.history_lines:54> local -a displays=( '6983  ps -aux | grep -v grep | grep zbctl | awk ''{print $2}'' | xargs kill                                                                ' '6984  ps -aux | grep -v grep | grep zbctl                                                                                                ' '6985  ps -aux | grep -v grep | grep worker                                                                                               ' '6986  docker ps -a                                                                                                                       ' '6987  docker system prune                                                                                                                ' '6988  docker ps -a                                                                                                                       ' '6989  cd dev                                                                                                                             ' '6990  atom .                                                                                                                             ' '6991  cd $(mktemp -d)                                                                                                                    ' '6992  ZDOTDIR=$PWD HOME=$PWD zsh -f                                                                                                      ' '6993  cd $(mktemp -d)                                                                                                                    ' '6994  ZDOTDIR=$PWD HOME=$PWD zsh -f                                                                                                      ' '6995  cd $(mktemp -d)                                                                                                                    ' '6996  cp /home/me/.zsh_history .                                                                                                     ' '6997  source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh                                         ' '6998  functions -T _autocomplete.history_lines                                                                                           ' )
+_autocomplete.history_lines:58> events=( 'ps -aux | grep -v grep | grep zbctl | awk ''{print $2}'' | xargs kill' 'ps -aux | grep -v grep | grep zbctl' 'ps -aux | grep -v grep | grep worker' 'docker ps -a' 'docker system prune' 'docker ps -a' 'cd dev' 'atom .' 'cd $(mktemp -d)' 'ZDOTDIR=$PWD HOME=$PWD zsh -f' 'cd $(mktemp -d)' 'ZDOTDIR=$PWD HOME=$PWD zsh -f' 'cd $(mktemp -d)' 'cp /home/me/.zsh_history .' 'source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh' 'functions -T _autocomplete.history_lines' ) 
+_autocomplete.history_lines:59> [[ history-search:autocomplete.history-lines:: == *-incremental-* ]]
+_autocomplete.history_lines:62> local _comp_no_ignore=1 expl
+_autocomplete.history_lines:63> _description -2V history-lines expl 'history line'
+_autocomplete.history_lines:64> compadd -2 -o nosort -J history-lines -QU -S ';' -R _autocomplete.history_lines.suffix -ld displays -a events
functions -T cd dev;
6983  ps -aux | grep -v grep | grep zbctl | awk '{print $2}' | xargs kill                                                                
6984  ps -aux | grep -v grep | grep zbctl                                                                                                
6985  ps -aux | grep -v grep | grep worker                                                                                               
6986  docker ps -a                                                                                                                       
6987  docker system prune                                                                                                                
6988  docker ps -a                                                                                                                       
6989  cd dev                                                                                                                             
6990  atom .                                                                                                                             
6991  cd $(mktemp -d)                                                                                                                    
6992  ZDOTDIR=$PWD HOME=$PWD zsh -f                                                                                                      
6993  cd $(mktemp -d)                                                                                                                    
6994  ZDOTDIR=$PWD HOME=$PWD zsh -f
```

BTW, with none or only one entry on history, first one is automaticaly selected.
```
 ~ $ cd $(mktemp -d)
/tmp/tmp.N2Ye5YvxXK $ ZDOTDIR=$PWD HOME=$PWD zsh -f
MY-LAPTOP% source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# pressing 2 times on ↑ (notice the weird "@" added after second press)
MY-LAPTOP% source^@/home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh;source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh;

MY-LAPTOP-132% history -p
# pressing one time on ↑ (don't change how many times pressed)
MY-LAPTOP-132% ;
```

**Comment by hardevine** [comment] 2021-01-15 07:56
i had #HIST_STAMPS="mm/dd/yyyy" enabled, after disabling its fixed

**Comment by seboudry** [comment] 2021-01-15 11:07
Doesn't have `HIST_STAMPS="mm/dd/yyyy"` enable though.
Nothing change (still bugy) with or whithout this.

**Comment by marlonrichert** [comment] 2021-01-15 17:33
@ShrirajHegde @seboudry @hardevine It should be fixed now. Please update and try it out.

**Comment by seboudry** [comment] 2021-01-15 19:04
Seems to be a lot better ! :+1: 

I have some weird behaviour with lines disappearing while browsing list.
I would have test zsh-autocomplete alone like before but got this error.
Can you tell me which other files to source?

```
~$ cd $(mktemp -d)
/tmp/tmp.5qpTNqTtuT$ ZDOTDIR=$PWD HOME=$PWD zsh -f                           
MY-LAPTOP% source /home/me/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
.autocomplete.__init__:33: command not found: add-zsh-hook
.autocomplete.compinit:224: command not found: add-zsh-hook
.autocomplete.config:111: command not found: add-zsh-hook
.autocomplete.widget:50: command not found: add-zsh-hook
.autocomplete.key:78: command not found: add-zsh-hook
.autocomplete.key-binding:57: command not found: add-zsh-hook
.autocomplete.recent-dirs:90: command not found: add-zsh-hook
.autocomplete.async:495: command not found: add-zsh-hook 
```

```

**Comment by marlonrichert** [comment] 2021-01-15 19:42
@seboudry Sorry, it seems I accidentally deleted something. Please update again; it should be fixed now.

**Comment by hardevine** [comment] 2021-01-16 08:54
as soon as i start new terminal tab:

compdef:1: command not found: .autocomplete.compinit.precmd
compdef:1: command not found: .autocomplete.compinit.precmd
compdef:1: command not found: .autocomplete.compinit.precmd
compdef:1: command not found: .autocomplete.compinit.precmd
compdef:1: command not found: .autocomplete.compinit.precmd

**Comment by marlonrichert** [comment] 2021-01-16 13:20
@hardevine It appears you found an edge case where I had a bug in the logic. It should be fixed now. Please update and try again.

**Closed by marlonrichert** 2021-01-16 13:20 UTC
Labels: Bug report

**Comment by hardevine** [comment] 2021-01-16 14:32
fixed, 
but, then this came :
```
Warning: `zstyle ':autocomplete:list-choices:*'` settings are no longer supported.
Please use `zstyle ':autocomplete:*'` for these settings instead.
```

then i changed in .autocomplete.config :10 
```
if (( ${#$(zstyle -L ':autocomplete:list-choices:*')} > 0 )); then
```
to
```
if (( ${#$(zstyle -L ':autocomplete:list-choices:*')} > 1 )); then
```

then it went away 🤷‍♂️

**Comment by ShrirajHegde** [comment] 2021-01-16 16:45
> @ShrirajHegde @seboudry @hardevine It should be fixed now. Please update and try it out.

yes, no longer happening, Thanks

**Comment by marlonrichert** [comment] 2021-01-16 21:02
> ```
> Warning: `zstyle ':autocomplete:list-choices:*'` settings are no longer supported.
> Please use `zstyle ':autocomplete:*'` for these settings instead.
> ```

@hardevine Yes, that’s a warning I’ve put there myself to tell you that you have an old setting in your `.zshrc` file that doesn’t do anything. You don’t have to report it here. Just remove that `zstyle` statement from your `.zshrc` file.

**Comment by hardevine** [comment] 2021-01-17 05:40
> > ```
> > Warning: `zstyle ':autocomplete:list-choices:*'` settings are no longer supported.
> > Please use `zstyle ':autocomplete:*'` for these settings instead.
> > ```
> 
> @hardevine Yes, that’s a warning I’ve put there myself to tell you that you have an old setting in your `.zshrc` file that doesn’t do anything. You don’t have to report it here. Just remove that `zstyle` statement from your `.zshrc` file.

but i dont have any zstyle statements in .zshrc

**Comment by marlonrichert** [comment] 2021-01-17 08:03
Hm, weird. But no matter: I removed the warning altogether. It’s been quite a while since I changed those settings anyway.

**Comment by seboudry** [comment] 2021-01-18 10:15
All good for me !!!
Thanks a lot ;)
