### ISSUE TITLE
Slight incompatibility with powerlevel10k theme

### ISSUE THREAD

**Issue by ShrirajHegde** [marlonrichert/zsh-autocomplete#166] opened 2021-01-11 15:11 UTC
## Environment
* `zsh-autocomplete` version: d728cf566bd0aba01b0a3937c781bbcb055b1bd0
* Zsh version: zsh-5.8-0-g77d203f 
* Framework: none 
* Plugin manager: none 
* `~/.zshrc` file: https://pastebin.com/6E0pP4MJ 

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* No 

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?
* [powerlevel10k](https://github.com/romkatv/powerlevel10k)

## Steps to reproduce

1. Use zsh-autocomplete along with powerlevel10k
2. Try some command like git or even cat

### Actual behavior
error/some warning

**Only when launched using history function in zsh-autocomplete by pressing  ↑** 

![image](https://user-images.githubusercontent.com/66936172/104198463-4366f280-544c-11eb-9e99-56b25319934a.png)
![image](https://user-images.githubusercontent.com/66936172/104199045-f6cfe700-544c-11eb-9881-4ffd65591618.png)

**Comment by ShrirajHegde** [comment] 2021-01-11 15:29
![image](https://user-images.githubusercontent.com/66936172/104201251-8d050c80-544f-11eb-837b-9fc2da74b0fe.png)


Happens with variety of commands.(not just git)

Powerlevel10k is in latest version (https://github.com/romkatv/powerlevel10k/commit/00232d1b6de0931fd9394bc3f963afb88644447d)

**Comment by tekhnee** [comment] 2021-01-11 18:58
Confirming this issue; except that the error messages on my end complained about `fd 20`.

**Comment by marlonrichert** [comment] 2021-01-11 19:16
@ShrirajHegde @tekhnee This is a problem in [P10k's `_p9k_deschedule_redraw()` function](https://github.com/romkatv/powerlevel10k/blob/33f20f5eaea0de5f08d77869f8cc087ddf798351/internal/p10k.zsh#L7457). It tries to uninstall an fd handler, without checking whether it's still installed, and tries to close an fd, without checking if it's still open. Please open an issue there.

**Comment by romkatv** [comment] 2021-01-11 19:42
@marlonrichert Does zsh-autocomplete invoke zle widgets in a fork? If so, it's indeed incompatible with powerlevel10k. If you can confirm this, I'll add a check to powerlevel10k so that it fails to initialize if zsh-autocomplete is loaded. This will prevent issues like this from being filed. Sounds good?

**Comment by romkatv** [comment] 2021-01-12 06:29
I took a look at the code. If my reading is correct, zsh-autocomplete can close random file descriptors (the ones it hasn't opened) and kill random processes (the ones it hasn't started). I've thrown together a fix in https://github.com/romkatv/zsh-autocomplete/tree/fix-rogue-fd-close-and-kill. I wasn't able to reproduce the original error message (the instructions in the issue description are incomplete), so I don't know if this actually fixes the problem. Give it a try.

> @ShrirajHegde @tekhnee This is a problem in [P10k's `_p9k_deschedule_redraw()` function](https://github.com/romkatv/powerlevel10k/blob/33f20f5eaea0de5f08d77869f8cc087ddf798351/internal/p10k.zsh#L7457). It tries to uninstall an fd handler, without checking whether it's still installed, and tries to close an fd, without checking if it's still open. Please open an issue there.

Either I'm misunderstanding this comment or it's wrong. The code you've linked to looks correct to me.

**Comment by marlonrichert** [comment] 2021-01-12 08:23
@romkatv Why exactly are you passing the names of the parameters instead of the values? How does that solve the problem?

**Comment by romkatv** [comment] 2021-01-12 08:25
> @romkatv Why exactly are you passing the names of the parameters instead of the values?

To avoid closing a file descriptor that hasn't been opened by zsh-autocomplete. I believe with the current code the following can happen:

1. zsh-autocomplete opens file descriptor 20.
2. zsh-autocomplete closes file descriptor 20.
3. Some other code open file descriptor 20.
4. zsh-autocomplete closes file descriptor 20.

**Comment by marlonrichert** [comment] 2021-01-12 08:28
And what is the reason for using anonymous functions inside the `kill` function?

**Comment by romkatv** [comment] 2021-01-12 08:31
> And what is the reason for using anonymous functions inside the `kill` function?

So that this works:

```zsh
function f() {}
local -i fd pid
exec {fd}< <(print $sysparams[pid])
read -ru $fd pid
zle -F $fd f 
.autocomplete.async.kill fd pid
```

**Comment by marlonrichert** [comment] 2021-01-12 08:40
Yes, I understand that’s what you’re trying to do. What I don’t understand, though: Why are the anonymous functions inside `.autocomplete.async.kill` necessary for that to work? What exactly do they accomplish?

**Comment by marlonrichert** [comment] 2021-01-12 08:42
Also, why do you prefer `read -u $1` over `read <$1`?

**Comment by romkatv** [comment] 2021-01-12 08:44
Without the anonymous functions the code snipped I've posted earlier wouldn't work. More specifically, `fd` and `pid` wouldn't be set to zero by `.autocomplete.async.kill`.

> Also, why do you prefer `read -u $1` over `read <$1`?

Faster and cleaner. I'm not attached to this code.

**Comment by eddyg** [comment] 2021-01-12 12:52
Thanks for digging in to this, Roman! 🎉 This was a low-level issue, and I’m sure it took some time to get up to speed so you could debug unfamiliar code. It is appreciated by the users of your excellent prompt framework.

**Comment by marlonrichert** [comment] 2021-01-12 14:17
@romkatv I left some questions on the code: https://github.com/marlonrichert/zsh-autocomplete/pull/169/files

**Comment by romkatv** [comment] 2021-01-12 14:24
> @romkatv I left some questions on the code: https://github.com/marlonrichert/zsh-autocomplete/pull/169/files

Where can I see them? The linked page doesn't have any comments/questions that I can see.

**Comment by marlonrichert** [comment] 2021-01-12 14:36
Hm, I wonder if only "collaborators" can see them?

No matter, I'll paste them here:

Why not do this?
```zsh
  if (( ${1-0} )); then
    local -i fd=${(P)1}
    zle -F $fd
    exec {fd}<&-
    typeset -g $1=
  fi

  if (( ${2-0} )); then
    local -i pid=${(P)2}
    [[ -o MONITOR ]] && (( pid *= -1 ))
    kill -KILL $pid 2>/dev/null
    typeset -g $2=
  fi
```
Would that not work?

Plus, why exactly is using `read -u $fd` is faster than `read <$fd`?

**Comment by marlonrichert** [comment] 2021-01-12 14:40
Oh, and why `typeset -g $1=`? Why not just `unset $1`?

**Comment by romkatv** [comment] 2021-01-12 14:48
> Why not do this?
> 
> ```shell
>   if (( ${1-0} )); then
>     local -i fd=${(P)1}
>     zle -F $fd
>     exec {fd}<&-
>     typeset -g $1=
>   fi
> 
>   if (( ${2-0} )); then
>     local -i pid=${(P)2}
>     [[ -o MONITOR ]] && (( pid *= -1 ))
>     kill -KILL $pid 2>/dev/null
>     typeset -g $2=
>   fi
> ```
> 
> Would that not work?

It won't work for the snippet I posted earlier. It will work for the real code because it never passed `fd` or `pid` as arguments.

> Plus, why exactly is using `read -u $fd` is faster than `read <$fd`?

Because it executes more code. If you are really curious, run a profiled on zsh.

By the way, the reason I didn't send a PR is because I don't want to spend a lot of time on it. If there is a chance you can fix this issue without my input, I'd very much appreciate it. The issue is not related to Powerlevel10k.

**Comment by marlonrichert** [comment] 2021-01-12 18:19
Sure, I won’t bother you with further questions. I just saw this as a good opportunity to learn something. Plus, I want to understand the code before I merge it. 🙂

Thank you for you contribution!

**Comment by tekhnee** [comment] 2021-01-12 18:31
@marlonrichert zsh scripting is out of my depth, but for what it's worth my local merge was catastrophic, with the familiar error now repeated on every single keystroke. I had to run `git reset --hard` only minutes later.

**Comment by marlonrichert** [comment] 2021-01-12 20:24
I can confirm that it doesn't work for me either:
```zsh
.autocomplete.async.kill:zle:5: No handler installed for fd 23
.autocomplete.async.kill:6: failed to close file descriptor 23: bad file descriptor
```

**Comment by romkatv** [comment] 2021-01-12 20:25
Wow, so many people can reproduce the problem. Can any of you post instructions?

**Comment by ShrirajHegde** [comment] 2021-01-12 20:51
> Wow, so many people can reproduce the problem. Can any of you post instructions?


to get the error,

press up-arrow to access history, press backspace to modify last/old command

**Comment by tekhnee** [comment] 2021-01-12 20:52
I've been too distracted by work to make out a pattern — sorry.

The only vector I can recall—among others, no doubt—is the following:

1. At the prompt, type a command that provides ZSH completions (I've tried with `cp` and `ls`).
     (Result: the `zsh-autocompletion` completions menu appears.) 
2. Press <kbd>tab</kbd> to enter the completions menu.
     (Result: completions menu active.)
3. Press <kbd>alt</kbd>+<kbd>.</kbd> to move to the last suggestion in the menu.
     (Result: **Error**)

**Comment by tekhnee** [comment] 2021-01-12 20:56
> press up-arrow to access history, press backspace to modify last/old command

Confirming that one, too.

**Comment by romkatv** [comment] 2021-01-12 20:56
I've installed Debian Buster. Then I ran these commands as root:

```zsh
apt-get update
apt-get install -y git zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
git clone --depth=1 https://github.com/marlonrichert/zsh-autocomplete.git
```

What's next?

**Comment by ShrirajHegde** [comment] 2021-01-13 06:42
> I've installed Debian Buster. Then I ran these commands as root:
> 
> ```shell
> apt-get update
> apt-get install -y git zsh
> git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
> git clone --depth=1 https://github.com/marlonrichert/zsh-autocomplete.git
> ```
> 
> What's next?

https://pastebin.com/6E0pP4MJ

source them like this and start terminal, press up arrow to scroll up history, then press backspace

**Comment by romkatv** [comment] 2021-01-13 07:47
Here's what I did:

1. Installed Debian Buster.
2. Ran these commands as root:
   ```bash
   apt-get update
   apt-get install -y curl zsh
   curl -fsSL https://pastebin.com/raw/6E0pP4MJ | tr -d '\r' >~/.zshrc
   zsh
   ```

Here's the result:

```text
/root/.zshrc:source:9: no such file or directory: /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
/root/.zshrc:source:10: no such file or directory: /home//programs-scripts/zsh-autocomplete/zsh-autocomplete.plugin.zsh
/root/.zshrc:source:11: no such file or directory: /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
/root/.zshrc:source:12: no such file or directory: /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

Please provide specific instructions that anyone can use without guessing what needs to be fixed in them. The instructions should start with "Install SOME_SPECIFIC_OS" and should follow with an unambiguous list of user actions such as running commands, pressing keys, etc. The OS can be anything you want, just make sure to specify the name and the version. The following commands and actions should assume that the person trying to follow your instructions has a pristine installation of the OS.

Before posting your instructions, verify that the problem reproduces if you follow these instructions yourself.

Ideally, the instructions should be minimal. For example, if your instructions involve the creation of zshrc, every line in that file should be instrumental to the reproduction of the problem. If the problem can be reproduced if some line is removed (e.g., the line that sources `zsh-syntax-highlighting.zsh`), then that line shouldn't be present in your instructions as it's not required to demonstrate the problem.

The requirement of minimalism is secondary. The most important part is that your instructions are unambiguous and that they reproduce the problem.

**Comment by ShrirajHegde** [comment] 2021-01-13 08:23
## Ok, assuming you have cloned to home
```zsh
#.zshrc
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi



# enable color support of ls and also add handy aliases
  if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      alias dir='dir --color=auto'
      alias vdir='vdir --color=auto'
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
  fi

# some more ls aliases
	alias ll='ls -alF'
	alias la='ls -A'
	alias l='ls -CF'


autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000(default) lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


source $HOME/powerlevel10k/powerlevel10k.zsh-theme
source $HOME/zsh-autocomplete/zsh-autocomplete.plugin.zsh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#ignoring commands starting with space in history
setopt HIST_IGNORE_SPACE

```

Try it now

**Comment by ShrirajHegde** [comment] 2021-01-13 08:25
> Here's what I did:
> 
> 1. Installed Debian Buster.
> 2. Ran these commands as root:
>    ```shell
>    apt-get update
>    apt-get install -y curl zsh
>    curl -fsSL https://pastebin.com/raw/6E0pP4MJ | tr -d '\r' >~/.zshrc
>    zsh
>    ```
> 
> Here's the result:
> 
> ```
> /root/.zshrc:source:9: no such file or directory: /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
> /root/.zshrc:source:10: no such file or directory: /home//programs-scripts/zsh-autocomplete/zsh-autocomplete.plugin.zsh
> /root/.zshrc:source:11: no such file or directory: /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
> /root/.zshrc:source:12: no such file or directory: /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> ```
> 
> Please provide specific instructions that anyone can use without guessing what needs to be fixed in them. The instructions should start with "Install SOME_SPECIFIC_OS" and should follow with an unambiguous list of user actions such as running commands, pressing keys, etc. The OS can be anything you want, just make sure to specify the name and the version. The following commands and actions should assume that the person trying to follow your instructions has a pristine installation of the OS.
> 
> Before posting your instructions, verify that the problem reproduces if you follow these instructions yourself.
> 
> Ideally, the instructions should be minimal. For example, if your instructions involve the creation of zshrc, every line in that file should be instrumental to the reproduction of the problem. If the problem can be reproduced if some line is removed (e.g., the line that sources `zsh-syntax-highlighting.zsh`), then that line shouldn't be present in your instructions as it's not required to demonstrate the problem.
> 
> The requirement of minimalism is secondary. The most important part is that your instructions are unambiguous and that they reproduce the problem.

everything else is same, the source path from home is to be adjusted accordingly

**Comment by ShrirajHegde** [comment] 2021-01-13 08:31
Ok, this is the exact one that should work for you else please adjust locations of `powerlevel10k.zsh-theme` and `zsh-autocomplete.plugin.zsh`

and try running as non root (haven't tried it in non root)
https://pastebin.com/NpCSTvWY

@romkatv

**Comment by ShrirajHegde** [comment] 2021-01-13 08:40
you don't need specific setup at all, just use any os, tested on Ubuntu and arch

```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
#add the `.zshrc` in the temp dir and the p10k settings from ./cache
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshel
```

just this much should work

**Comment by ShrirajHegde** [comment] 2021-01-13 08:41
or just temporarily replacing given .zshrc with yours should work well too

**Comment by romkatv** [comment] 2021-01-13 08:53
Here's what I did:

1. Installed Debian Buster.
2. Ran these commands as root:
   ```bash
   apt-get update
   apt-get install -y curl git sudo zsh
   useradd -ms /bin/zsh test
   cd ~test
   sudo -u test git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
   sudo -u test git clone --depth=1 -b fix-rogue-fd-close-and-kill https://github.com/romkatv/zsh-autocomplete.git
   curl -fsSL https://pastebin.com/raw/NpCSTvWY | tr -d '\r' | sudo -u test tee .zshrc >/dev/null
   su -l test
   ```
3. This screen appeared: 
![image](https://user-images.githubusercontent.com/1282067/104427334-67791f80-5583-11eb-906e-4a9abb226a55.png)
4. I pressed <kbd>q</kbd>.
5. This screen appeared: 
![image](https://user-images.githubusercontent.com/1282067/104428461-ce4b0880-5584-11eb-8c9b-2fe1cb94cd40.png)
6. I pressed <kbd>Up</kbd>.
7. This screen appeared: 
![image](https://user-images.githubusercontent.com/1282067/104428523-e1f66f00-5584-11eb-8189-34926bb6f9f3.png)
8. I pressed <kbd>Backspace</kbd>.
9. This screen appeared: 
![image](https://user-images.githubusercontent.com/1282067/104428588-f20e4e80-5584-11eb-9279-e5029924b261.png)

There was no error.

Please provide instructions that will reproduce the issue if I follow them exactly. **Before posting them, verify that they reproduce the issue if you follow them yourself.**

**Comment by ShrirajHegde** [comment] 2021-01-13 09:11
all the steps are accurate, just make some history

your history is empty in zsh

this error occurs more often when you are not in $HOME, co maybe cd into Downloads or somewhere



maybe copy bash history to zsh history and then press `up`,when `zsh-autocomplete` completes some command, press backspace

like this,

- step 1:
![image](https://user-images.githubusercontent.com/66936172/104430508-c43d0000-55ac-11eb-8fe2-56a5f048ae89.png)
- step 2
press backspace
![image](https://user-images.githubusercontent.com/66936172/104430579-e040a180-55ac-11eb-973d-7f24b297052d.png)
step 3:

now just try executing cd Desptop/downloads via `Up` arrow 

![image](https://user-images.githubusercontent.com/66936172/104430758-1d0c9880-55ad-11eb-8be0-9672af1e6ce9.png)

**Comment by romkatv** [comment] 2021-01-13 09:15
I don't have `~/Desktop`. If it's necessary to have this directory in order to reproduce the issue, include the creation of this directory in your instructions.

Please post specific instruction that I and everyone else can follow without improvising. Without "maybe" steps.

**Comment by ShrirajHegde** [comment] 2021-01-13 09:19
![image](https://user-images.githubusercontent.com/66936172/104431837-5db8e180-55ae-11eb-9085-87d7a447b2b2.png)


Any subdir from home works 
I guess root account has .config folder atleast

**Comment by romkatv** [comment] 2021-01-13 09:28
Here's what I did:

1. Installed Debian Buster.
2. Ran these commands as root:
   ```bash
   apt-get update
   apt-get install -y curl git sudo zsh
   useradd -ms /bin/zsh test
   cd ~test
   sudo -u test mkdir Desktop
   sudo -u test git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
   sudo -u test git clone --depth=1 -b fix-rogue-fd-close-and-kill https://github.com/romkatv/zsh-autocomplete.git
   curl -fsSL https://pastebin.com/raw/NpCSTvWY | tr -d '\r' | sudo -u test tee .zshrc >/dev/null
   su -l test
   ```
3. Pressed <kbd>q</kbd> to exit Powerlevel10k Configuration Wizard.
4. Pressed <kbd>Up</kbd>.
5. Pressed <kbd>Backspace</kbd>.
6. This screen appeared: ![image](https://user-images.githubusercontent.com/1282067/104432770-a14d2480-5589-11eb-9759-b686f7183ca1.png)

There was no error.

I've ran out of time budget on this issue. I won't see future comments here unless you explicitly mention me. Don't hesitate to do that when you believe that my input is necessary and there is low chance that my time will be wasted.

**Comment by tekhnee** [comment] 2021-01-13 09:45
@romkatv if you are still interested and able to look into this, kindly repeat the procedure of your last post, also prepending your `~/.zshrc` with the following two lines:

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
 source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

I'm confident this should reproduce the issue (but please don't take me to court if it doesn't).

Thanks as ever.

**Comment by romkatv** [comment] 2021-01-13 09:48
@tekhnee This won't make a difference because `${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh` doesn't exit.

We could save a lot of time if you did the following:

1. Wrote unambiguous instructions that anyone can execute. See my comments for several examples of how they would look. In my instructions I use Debian Buster but you can specify any OS you like.
2. Before posting the instructions, verified that the issue reproduces if you follow them yourself.

**Comment by tekhnee** [comment] 2021-01-13 21:54
@ShrirajHegde I've been drilling down towards a reliable reproduction procedure.

No success so far, but two observations:

1. Today I'm no longer able to reproduce your pattern: <kbd>&#8593;</kbd> followed by <kbd>backspace</kbd>. 

2. If I stop using `zsh-autosuggestions`, my own pattern can no longer be reproduced, either. To recall, my own pattern was <kbd>PageDown</kbd> followed by  <kbd>Alt</kbd>-<kbd>,</kbd>.

Could you try my pattern on your system, also toggling your `zsh-autosuggestions`?

Thanks.

**Comment by ShrirajHegde** [comment] 2021-01-13 21:56
Yeah, I'll try it tomorrow (3:25 am here)

**Comment by marlonrichert** [comment] 2021-01-15 17:31
@ShrirajHegde @tekhnee @eddyg It should be fixed now. Please update and try it out.

**Comment by tekhnee** [comment] 2021-01-15 18:32
It does, thank you @marlonrichert.

(I had vain hopes that this would automagically also fix the transient prompt feature of p10k. If there is any actual evidence that the two issues might be related, I'll report back here. Otherwise this issue may be closed, as far as I'm concerned.)

**Closed** 2021-01-15 19:34 UTC
Labels: Bug report
