### ISSUE TITLE
recent dirs completion sometimes doesnt show 

### ISSUE THREAD

**Issue by fhill2** [marlonrichert/zsh-autocomplete#225] opened 2021-03-16 04:18 UTC
* `zsh-autocomplete` version: 85fdb5750d6bddc621df6ba447027c97fadf2bd4
* Zsh version: zsh-5.8.0-g77d203f
* Framework: None
* Plugin manager: Zplug

```
cd $(mktemp -d)
ZDOTDIR=$PWD HOME=$PWD exec zsh -f
source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
***problem still exists***
```

When using zoxide or z.lua, recent dirs completion sometimes doesnt show when using cd.
`cd <tab>`
Sometimes the completion will be available, and after zsh restart the completion won't show.

Executing `_zlua --complete` shows  /home/user/.config/nvim in database, 
`cd nvim` doesnt show the path in recent dirs completon.

`type -f _autocomplete.recent_dirs` output:
```zsh
_autocomplete.recent_dirs () {
        reply=("${(@)${(f)$( _zlua --complete $1 2>/dev/null )}##<->[[:space:]]##}")
}
```

cd space`^Xh` output:
```
tags in context :completion::autocomplete.ancestor-dirs:::
    ancestor-directories  (_autocomplete.ancestor_dirs _ftb__main_complete -ftb-complete .autocomplete._main_complete)
tags in context :completion::autocomplete.recent-paths:::
    recent-directories recent-files  (_autocomplete.recent_paths _ftb__main_complete -ftb-complete .autocomplete._main_complete)
tags in context :completion::complete:cd::
    directories  (_cd)
tags in context :completion::complete-fuzzy:cd::
    directories  (_cd)
tags in context :completion::history:::
    history-words  (.autocomplete._wanted _history _ftb__main_complete -ftb-complete .autocomplete._main_complete)
```

**Comment by marlonrichert** [comment] 2021-03-16 18:43
@fhill2 Can you make me a reproducible test case, please, using the bug report template that was there when you made a new issue? Here it is again: 
```zsh
 # Make sure you always test with the `main` branch.
$ git -C /path/to/zsh-autocomplete switch main

# Update to the latest commit.
$ git -C /path/to/zsh-autocomplete pull

# Create a temp dir and enter it.
$ cd $(mktemp -d)

# Restart Zsh without config files in this dir.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f

# Source the plugin.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Test and document the steps that reproduce the problem.
% <insert your steps to reproduce here>
```
You need to be more specific than "sometimes doesnt show" and "Sometimes the completion will be available". If I cannot reproduce it, then I cannot fix it. 🙂

**Comment by fhill2** [comment] 2021-03-17 06:08
# Make sure you always test with the `main` branch.
$ git -C /path/to/zsh-autocomplete switch main

# Update to the latest commit.
$ git -C /path/to/zsh-autocomplete pull

# Create a temp dir and enter it.
$ cd $(mktemp -d)

# Restart Zsh without config files in this dir.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f

# Source the plugin.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Test and document the steps that reproduce the problem.
% mkdir d
% ls                        # shows folder 'd' - nothing else in folder
% cd d                    # shows d folder in completion menu, with no other results from 'recent dirs'
% cd n                    # shows results from recent dirs matching 'n'


It seems as though autocomplete only shows 'recent dirs' completion matches  if 'directory' completion matches are empty.
If there is a folder in the current directory matching the argument of cd, recent dirs completion doesn't match.

Is this intended behaviour?

**Comment by marlonrichert** [comment] 2021-03-17 08:18
Yes, that is intended behavior, for a couple of technical reasons that I won't go into here. However, I can see how that's not always the desirable behavior. I'll have a look if I can improve it somehow.

**Comment by marlonrichert** [comment] 2021-03-22 21:29
@fhill2 Please check out the [`dirs`](https://github.com/marlonrichert/zsh-autocomplete/tree/dirs) branch and let me know if that works any better for you.

**Comment by fhill2** [comment] 2021-03-23 00:27
@marlonrichert Thank you for this update.

So far the tests below show the same behaviour as before for recent-dirs completion, tested with zsh-z, z.lua, autojump.

```
git -C /path/to/zsh-autocomplete pull
git -C /path/to/zsh-autocomplete switch dirs
git -C /path/to/zsh-autocomplete branch -v # shows dirs as active branch

# zsh-z test
cd $(mktemp -d)
ZDOTDIR=$PWD HOME=$PWD exec zsh -f
source /home/f1/.zplug/repos/agkozak/zsh-z/zsh-z.plugin.zsh
source /home/f1/.zplug/repos/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
type -f _autocomplete.recent_dirs # function set to zsh-z --complete
ls # directory empty
mkdir n
cd n # only shows n directory
cd nvim # displays recent-dir completion results


# autojump test
cd $(mktemp -d)
ZDOTDIR=$PWD HOME=$PWD exec zsh -f
 [[ -s /home/f1/.autojump/etc/profile.d/autojump.sh ]] && source /home/f1/.autojump/etc/profile.d/autojump.sh
source /home/f1/.zplug/repos/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
type -f _autocomplete.recent_dirs # function set to autojump --complete
ls # directory empty
mkdir n
cd n # only shows n directory
cd nvim # displays recent-dir completion results
```

I'm guessing these changes are to do with using recent-dirs without an external source (z.lua / zsh-z etc).

What differences should I be looking for?  (my understanding of the changes in the dirs branch are limited)

**Comment by marlonrichert** [comment] 2021-03-23 09:06
Sorry, but how do you even get recent dirs completions with those test cases? You have not actually visited the `nvim` dir in those shells. Here's what it looks like for me:
```zsh
$ cd $(mktemp -d)
$ mkdir nvim
$ source /Users/marlon/Git/zsh-z/zsh-z.plugin.zsh
$ cd nvim
$ z -l
89985      /private/var/folders/24/37_vm48s2tz9bhmj1rzffvl40000gn/T/tmp.pD2jXrVa/nvim
$ ZDOTDIR=$PWD HOME=$PWD PS1='%# ' exec zsh -f
% source /Users/marlon/Git/zsh-z/zsh-z.plugin.zsh
% z -l
%
```
As you can see, the new shell has its own list of recent dirs, which is empty. If you are getting `nvim` as a recent dir in the new shell, then you are not following the steps I've given exactly.

**Comment by fhill2** [comment] 2021-03-23 21:16
You are exactly right. An error on my part regarding my previous zsh-z test.
When repeating the tests:
zsh-z has its own list of recent dirs when launching a new shell.
autojump has the same list of recent dirs when launching a new shell.

```zsh
zsh-z test:
$ cd $(mktemp -d)
$ mkdir nvim
$ source /home/f1/.zplug/repos/agkozak/zsh-z/zsh-z.plugin.zsh
$ cd nvim
$ z -l # shows 20+ results including: /home/f1/.config/nvim
$ ZDOTDIR=$PWD HOME=$PWD PS1='%# ' exec zsh -f
% source /home/f1/.zplug/repos/agkozak/zsh-z/zsh-z.plugin.zsh
% z -l # empty


autojump test:
$ cd $(mktemp -d)
$ mkdir nvim
$ source /home/f1/.autojump/etc/profile.d/autojump.sh
$ cd nvim
$ autojump -s # 40+ results including: /home/f1/.config/nvim
$ ZDOTDIR=$PWD HOME=$PWD PS1='%# ' exec zsh -f
% source /home/f1/.autojump/etc/profile.d/autojump.sh
% autojump -s # 40+ results including: /home/f1/.config/nvim

```

**Comment by marlonrichert** [comment] 2021-03-23 22:10
Should be fixed now.

**Closed by marlonrichert** 2021-03-23 22:10 UTC
Labels: enhancement
