### ISSUE TITLE
 Recent dirs completion doesn't work with `zoxide` or `z.sh`

### ISSUE THREAD

**Issue by Martinits** [marlonrichert/zsh-autocomplete#410] opened 2022-01-21 12:00 UTC
I can use zoxide (or z) in my zsh (with oh-my-zsh) as usual, but I cannot see any completion about recent directory.
There's no "recent directory" title in the completion output, like "alias" or "external command".

Lines related to zsh-autocomplete in `.zshrc` are:
```zsh
zstyle ':autocomplete:*' recent-dirs zoxide
source ~/.zsh-plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
Full `.zshrc` is at https://github.com/Martinits/dotfiles/blob/master/.zshrc

When not set `zstyle ':autocomplete:*' recent-dirs zoxide` (use default cdr), recent dir completion works.
But zoxide and z.sh doesn't work.

Thanks a lot for helping or pointing out my mistakes!

### Environment

```zsh
pc linux-gnu /bin/zsh /bin/zsh zsh-5.8-0-g77d203f

0b993ff (grafted, HEAD -> main, origin/main, origin/HEAD) Make description color work in more terminals
```

### Steps to reproduce
In the test environment, it is nice.

**Comment by marlonrichert** [comment] 2022-01-21 12:54
Can you please share the output of `zoxide query --list` and `_z -l`?

**Comment by Martinits** [comment] 2022-01-21 12:58
> Can you please share the output of `zoxide query --list` and `_z -l`?

$ zoxide query --list
/home/martinit/my/tmp
/home/martinit/my/dotfiles
/home/martinit/my
/home/martinit/.config/alacritty
/home/martinit/my/mit6s081/lab
/home/martinit/.config/ranger
/home/martinit/my/mit6s081/lab/kernel
/vm/sharedfolder/quaderno/Docs/linuxuser/vim
.........(many lines)

$ _z -l
![image](https://user-images.githubusercontent.com/48900241/150530767-d073eb8f-39b9-4cdd-90a8-dfe7c0b294e5.png)

**Comment by marlonrichert** [comment] 2022-01-21 13:01
Did you press Enter after typing `_z -l`?

**Comment by Martinits** [comment] 2022-01-21 13:04
> Did you press Enter after typing `_z -l`?

Yes I did. If not, it's like this:
![image](https://user-images.githubusercontent.com/48900241/150531716-a988864b-95ab-490f-98c1-a5ee8d570ab1.png)

**Comment by marlonrichert** [comment] 2022-01-21 13:05
OK, that's unexpected. `z.sh` doesn't normally use `fzf`, does it?

**Comment by marlonrichert** [comment] 2022-01-21 13:07
Try the following:
1. Run `functions -T _autocomplete.recent_directories`.
2. Generate some directory completions.
3. Check the contents of the file that `$_autocomplete__log` points at.

What do you see in the log?

**Comment by Martinits** [comment] 2022-01-21 13:24
> OK, that's unexpected. `z.sh` doesn't normally use `fzf`, does it?

I decided to use zoxide, so I removed z.sh(forget to tell you).
That _z command probably comes from zoxide, not z.sh.

**Comment by Martinits** [comment] 2022-01-21 13:29
> Try the following:
> 
> 1. Run `functions -T _autocomplete.recent_directories`.
> 2. Generate some directory completions.
> 3. Check the contents of the file that `$_autocomplete__log` points at.
> 
> What do you see in the log?

1. The command exited with non-zero value, no output.
2. done
3. 
```
$ cat `echo $_autocomplete__log`
TRAPINT:zle:2: can only be called from widget function
```

**Comment by marlonrichert** [comment] 2022-01-24 11:53
> 2. Generate some directory completions.

I meant, generate some "recent directory" completions, not just regular directory completions. Can you please repeat the steps with that adjustment?

**Comment by Martinits** [comment] 2022-01-24 14:28
I entered some directory like aaa/bbb/ccc, then `cd` to somewhere else, then `cd cc`(without Enter), now the recent dir completion for `aaa/bbb/ccc` should show up, is that right? But it didn't show up when I use zoxide or z (It showed up when using `cdr`, the default one)
And it seems that there's no function called _autocomplete.recent_directories, so when I did the first step, it exited with 1. Therefore, the log is empty this time.
But there's a function called `_autocomplete.recent_paths`, so I traced it with `functions -T _autocomplete.recent_paths`. Then generated some recent dir completion like what I said above. Log's here:
```
# 8. _autocomplete.recent_paths [22:16:12.222]
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret

# 10. _autocomplete.recent_paths [22:16:27.209]
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret

# 8. _autocomplete.recent_paths [22:16:30.910]
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret

# 10. _autocomplete.recent_paths [22:16:30.917]
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret

# 8. _autocomplete.recent_paths [22:16:31.040]
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret

# 10. _autocomplete.recent_paths [22:16:31.047]
5 ->1	((  compstate[nmatches]  ))
8 ->1	local -PaU files=( )
9	local -Pi ret=1
10	local -P tag=''
11	for tag=directories
12	for if [[ -v 'functions[_autocomplete.recent_directories]' ]]
11	for tag=files
12	for if [[ -v 'functions[_autocomplete.recent_files]' ]]
22	return ret
```
Wish I can provide something useful.

**Comment by marlonrichert** [comment] 2022-01-25 07:32
> And it seems that there's no function called _autocomplete.recent_directories

Aha, thanks! It appears I need to update the code that tries to detect whether Zoxide is loaded.

**Comment by marlonrichert** [comment] 2022-02-20 20:08
@Martinits I'm unable to reproduce this. Can you put together a reproducible test case for me? Otherwise, I cannot fix it.

**Comment by marlonrichert** [comment] 2022-04-20 13:34
Closing, as I'm unable to reproduce it.

**Closed by marlonrichert** 2022-04-20 13:34 UTC
Labels: invalid, question
