### ISSUE TITLE
soft links error

### ISSUE THREAD

**Issue by dimmonn** [marlonrichert/zsh-autocomplete#574] opened 2023-04-11 10:59 UTC
- [ ] I have carefully read all of the instructions in this issue template.
- [ ] I have carried them out to the letter.

Failure to do so can result in your issue being closed.

## Environment
```zsh
typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

* Operating system: macos
* Terminal emulator:iterm

- [ ] I have filled out the fields above.
- [ ] I have ran the commands in the code block above.
- [ ] I have pasted their output into the same block.

## Steps to reproduce
when i install at mac (either automatic or manual)
i get the below errors and terminal gets hung

```
.autocomplete.async.complete.fd-widget:3: not a directory: XXXX.local/state/zsh-autocomplete/log/2023-04-11.log
➜  ~
.autocomplete.async.complete.fd-widget:3: not a directory:XXXXlocal/state/zsh-autocomplete/log/2023-04-11.log
➜  ~
.autocomplete.async.complete.fd-widget:3: not a directory: XXXX/local/state/zsh-autocomplete/log/2023-04-11.log
➜  ~
.autocomplete.async.complete.fd-widget:3: not a directory: XXXX/.local/state/zsh-autocomplete/log/2023-04-11.log
➜  ~
```

**Comment by EwiththeBowtie** [comment] 2023-04-11 21:51
Reproduced on Oracle Linux 8

**Comment by marlonrichert** [comment] 2023-05-01 19:31
Duplicate of #571.

**Closed by marlonrichert** 2023-05-01 19:31 UTC
Labels: bug
