### ISSUE TITLE
Not able to change directories without cd. 

### ISSUE THREAD

**Issue by TanishBansal** [marlonrichert/zsh-autocomplete#16] opened 2020-05-06 09:59 UTC
Not able to cd to a directory without cd, permission denied. 
Without plugin.
tanish@us01:tanish/tanish_main1                                                     
▶ IOR
tanish/tanish_main1/IOR

With plugin.
tanish@us01:tanish/tanish_main                                                         
▶ IOR
zsh: permission denied: IOR

**Comment by TanishBansal** [comment] 2020-05-06 10:04
Why is **unsetopt AUTO_CD** required for the plugin to work?

**Comment by marlonrichert** [comment] 2020-05-06 10:12
It’s not strictly required. I can remove it.

**Comment by marlonrichert** [comment] 2020-05-06 18:04
@TanishBansal It's gone now. Please `git pull` to update. 🙂

**Comment by CallumHoward** [comment] 2020-05-07 08:40
With the current master, and as noted by @hliu202 I still need to `setopt AUTO_CD` after zsh-autocomplete is sourced, though I didn't set it previously

**Comment by marlonrichert** [comment] 2020-05-07 08:55
Ah, I think I know what the problem is. I probably introduced it in 0d3ff05933a7e1482e01399c73e8532030ababaf. I think I know how to fix it.

Thanks!

**Comment by marlonrichert** [comment] 2020-05-07 09:45
@CallumHoward I pushed in a new fix. Please try again. 🙂

**Comment by CallumHoward** [comment] 2020-05-07 11:52
Huh, I tried it and it causes my shell to exit before the first command gets executed.

**Comment by marlonrichert** [comment] 2020-05-07 11:53
What else are you using? If you comment out everything else in your `.zshrc`, does it still happen? Something might be conflicting with what `zsh-autocomplete` is doing.

**Comment by CallumHoward** [comment] 2020-05-07 12:10
yep, narrowed it down to https://github.com/zdharma/fast-syntax-highlighting

**Comment by marlonrichert** [comment] 2020-05-07 12:34
Thanks, I'll test it.

**Comment by marlonrichert** [comment] 2020-05-07 12:49
I tried it and although https://github.com/softmoth/zsh-vim-mode/ didn't make my shell exit, it did cause all kinds of other problems in `zsh-autocomplete`.

I found a solution for it, though: You need to source `zsh-vim-mode` *after* `zsh-autocomplete`. Otherwise, its [keymap tracking feature](https://github.com/softmoth/zsh-vim-mode/#editing-keymap-tracking) will undo some of the work that `zsh-autocomplete` does.

**Comment by CallumHoward** [comment] 2020-05-07 12:53
Huh, I was already sourcing it after. Perhaps it is another setting somewhere, I'll try and narrow it down some more.

**Comment by marlonrichert** [comment] 2020-05-07 12:58
Actually, after some more testing, I find that even if I change the order of sourcing the two, `zsh-vim-mode` _still_ messes up some of `zsh-autocomplete` features. So, scratch that.

Have you tried adding `VIM_MODE_TRACK_KEYMAP=no` to your `.zshrc`?

**Comment by marlonrichert** [comment] 2020-05-07 13:06
The only way I can find to stop `zsh-vim-mode` from messing with `zsh-autocomplete` is to
1. Set `VIM_MODE_TRACK_KEYMAP=no`.
1. Source `zsh-vim-mode` _before_ `zsh-autocomplete`.

But I'm closing this issue now, because the discussion is going really off topic. Feel free to open a new one. 🙂

**Closed by marlonrichert** 2020-05-07 13:06 UTC

**Comment by CallumHoward** [comment] 2020-05-07 13:11
Sourcing it after seemed to fix it, all seems to be working well now without the need for `setopt AUTO_CD` also. Thanks for your help!

**Comment by marlonrichert** [comment] 2020-05-07 13:11
OK, sourcing it after still led to some unexpected results for me, but I'm glad it works for you. 🙂
