### ISSUE TITLE
Recent directories completion doesn't work with cdr

### ISSUE THREAD

**Issue by okuramasafumi** [marlonrichert/zsh-autocomplete#442] opened 2022-06-02 19:05 UTC
## Environment

```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1

apple darwin21.0 /bin/zsh -zsh zsh-5.8.1-0-g1a490c7
/Users/okuramasafumi/.local/share/zinit/zinit.git/zinit.zsh:1633
/Users/okuramasafumi/.local/share/zinit/zinit.git/zinit.zsh:1271
/Users/okuramasafumi/.local/share/zinit/zinit.git/zinit.zsh:2688
/Users/okuramasafumi/.zshrc:52
5b0073d (HEAD -> main, origin/main, origin/HEAD) Check that `$ZSH_COMPDUMP` file can be read
```
* Operating system: macOS 12.4
* Terminal emulator: iTerm2 3.5.0beta5

Customization:
```
zstyle ':autocomplete:*' insert-unambiguous yes
zstyle ':autocomplete:*' widget-style menu-select
zstyle ':autocomplete:*' fzf-completion yes
```

## Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

% mkdir one
% cd one
% cd
% cd
directory
one/               zsh-autocomplete/
```

## Description

I enable `cdr` with the code below:

```sh
if is-at-least 4.3.11; then
  autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
  add-zsh-hook -Uz chpwd chpwd_recent_dirs
  zstyle ":chpwd:*" recent-dirs-max 500
  zstyle ":chpwd:*" recent-dirs-defalut true
  zstyle ":completion:*" recent-dirs-insert always
fi
```

I'm sure `cdr` works since running `cdr` command prints correct directories.
However, typing `cd` just prints directory candidates only, not recent dirs.

I debugged it and found that `_autocomplete.recent_paths()` function in `functions/completion/_autocomplete.recent_paths` file is called but no paths were added. `$_comp_tags` was empty so I suspect it might be a cause.

**Comment by marlonrichert** [comment] 2022-06-03 12:47
Duplicate of #432.

**Closed by marlonrichert** 2022-06-03 12:47 UTC
Labels: bug

**Comment by okuramasafumi** [comment] 2022-06-04 09:48
On #432 you said we should enable `cdr` manually by `autoload -Uz cdr`. I did that but it still doesn't work.

**Comment by marlonrichert** [comment] 2022-06-14 12:18
@okuramasafumi Please post on #432.
