### ISSUE TITLE
Show part of the completions list instead of "Too long list" message

### ISSUE THREAD

**Issue by mehanoid** [marlonrichert/zsh-autocomplete#109] opened 2020-10-14 20:48 UTC
### Is your feature request related to a problem? Please describe.

Currently if there is not enough space on the terminal, then the message "Too long list" is displayed, which is not very informative.

### Describe the solution you'd like

It would be great if at least part of the list was displayed, up to `max-lines` with the message "Not all lines are shown. Down Arrow to expand" or something like that.

### Describe alternatives you've considered
May be this feature should be optional, although it seems to me it would not bother anyone.

**Comment by marlonrichert** [comment] 2020-10-15 08:31
I would love to have that myself, but Zsh’s completion unfortunately makes it really hard to do. I’ll keep this issue open, as it’s on my own wishlist, too, but please don’t expect an implementation any time soon. 🙂

**Comment by mehanoid** [comment] 2020-10-15 09:16
Yes, I understand, and it's a great plugin anyway :smiley: Thank you!

**Comment by marlonrichert** [comment] 2020-10-30 22:19
@mehanoid @wolfo @Abhishek12345679 I got inspired while reading some code, the solution popped into my head, and then I implemented it. Enjoy!

**Comment by mehanoid** [comment] 2020-10-30 23:13
Wow, it works! :star_struck: Really cool, thank you! :smiley:

**Comment by wolfo** [comment] 2020-10-31 01:22
Doesn't quite work for me. The menu shows up, but is cut off after 9 items or rows. When I go past the last item, it goes straight back to the first one.

And there's no color highlighting in this case, though it's not that important.

Ex. 1
```
$ ls Library/
Accessibility         Autosave Information  ContainerManager      Favorites             HomeKit
Accounts              Caches                Containers            FontCollections       IdentityServices
Application Scripts   Calendars             Cookies               Fonts                 Input Methods
Application Support   CallServices          CoreFollowUp          FrontBoard            Internet Plug-Ins
ApplicationSupport    ColorPickers          DES                   GameKit
Assistant             ColorSync             DataDeliveryServices  Google
Assistants            Colors                Developer             Group Containers
Audio                 Compositions          Dictionaries          HTTPStorages
```

Ex. 2
```
$ antigen update
apply       Load all bundle completions
bundle      Install and load the given plugin
bundles     Bulk define bundles
cache-gen   Generate cache
cleanup     Clean up the clones of repos which are not used by any bundles currently loaded
init        Load Antigen configuration from file
list        List out the currently loaded bundles
purge       Remove a cloned bundle from filesystem
reset       Clears cache
```

These are my only zsh-autocomplete options:
```
zstyle ':autocomplete:list-choices:*' min-input 3
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
zstyle ':completion:*' tag-order '! history-words' '-'
```

**Comment by marlonrichert** [comment] 2020-10-31 08:11
@wolfo Yeah, it doesn’t work that way. Try adding this to your `~/.zshrc`:
```zsh
zstyle ':completion:*' group-name ''
```
This enables completion group headers, which now includes a helpful shortcut hint when the list is truncated:
```
(partial list; press Control + Space for more)
```

But thanks for the feedback. I’ll see if I can somehow show that hint when group headers are not in use, too.

**Comment by marlonrichert** [comment] 2020-10-31 08:13
@wolfo 

> And there's no color highlighting in this case, though it's not that important.

That is odd. How have configured your color highlighting? Can you please add screenshots here, one with the problem and one without?

**Comment by marlonrichert** [comment] 2020-10-31 12:28
@wolfo It now shows a hint to press <kbd>Control</kbd><kbd>Space</kbd>, even when completion group headers would otherwise not be shown.

Let me know if you're still experiencing the color issue and if you do, please add screenshots here of before and after, so I can get an idea of what the problem might be.

**Comment by wolfo** [comment] 2020-10-31 12:50
Yes, it does show the hint now. Control+Space works for me, as long as I reduce my zshrc to this:
```
source ~/.antigen/bundles/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':autocomplete:list-choices:*' min-input 3
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
zstyle ':completion:*' tag-order '! history-words' '-'
```
So I'll have to hunt down my .zshrc further.

However, the colors are like this:
![complete and with colors](https://user-images.githubusercontent.com/940176/97779394-00e88600-1b7e-11eb-84d8-3d95f046f78f.png)
![incomplete and without colors](https://user-images.githubusercontent.com/940176/97779395-0219b300-1b7e-11eb-98c1-56a0357161d9.png)

**Comment by marlonrichert** [comment] 2020-10-31 14:58
@wolfo What happens when you press <kbd>Control</kbd><kbd>Space</kbd> in that last screenshot? Do the colors return?

**Comment by marlonrichert** [comment] 2020-10-31 15:01
> Control+Space works for me, as long as I reduce my zshrc to this

In the situation that Control+Space doesn’t work for you, what output do you get from `bindkey '^@'`?

**Comment by wolfo** [comment] 2020-10-31 15:19
> > Control+Space works for me, as long as I reduce my zshrc to this
> 
> In the situation where Control+Space doesn’t work for you, what output do you get from `bindkey '^@'`?

I get "undefined-key". I see that if I source zsh-autocomplete at the end of .zshrc, it is instead list-expand, and it works now. I think I activated vi-keys or something before, which overwrote the binding. My bad!

So with that out of the way, Ctrl+Space does expand the list and brings back the colors.

Now it would only be nice if the unexpanded list also showed colors :-) Or maybe it's just me. But anyway, I know it's a very fresh feature, thank you for that.

**Comment by wolfo** [comment] 2020-10-31 15:19
Kind of related, I don't notice `zstyle ':autocomplete:list-choices:*' max-lines 100%` in zshrc making any difference. Whatever the value (I even tried >100%), it's always the hint (one line) and the first part of the results (9 lines). It seems like this should be the deciding factor whether the output gets abridged, right?

**Comment by leoddd** [comment] 2020-10-31 16:10
I know this might not be quite the right place to mention this, but I was just setting this plugin up and also could not get `zstyle ':autocomplete:list-choices:*' max-lines` or `zstyle ':autocomplete:list-choices:*' min-input` to have any effect. I can see the options are set in zstyle, but suggestions still pop up after just 1 character and take up more lines than I specify.

Also, the fact that this plugin eats inputs with its "do you wish to see all n possibilities" query makes it really hard to use in my tmux setup, wish that could be disabled as well.

**Comment by wolfo** [comment] 2020-10-31 17:00
Actually, I can confirm everything leo says, including the input eating.

**Comment by marlonrichert** [comment] 2020-10-31 21:33
> Also, the fact that this plugin eats inputs with its "do you wish to see all n possibilities" query makes it really hard to use in my tmux setup, wish that could be disabled as well

If you're seeing that, there is something really wrong with your setup. You should _never_ see that message while using `zsh-autocomplete`. Did you restart your terminal yet after installing `zsh-autocomplete`? And I mean really _restart._ Do **not** `source ~/.zshrc`.

**Comment by marlonrichert** [comment] 2020-10-31 21:46
> I know this might not be quite the right place to mention this, but I was just setting this plugin up and also could not get `zstyle ':autocomplete:list-choices:*' max-lines` or `zstyle ':autocomplete:list-choices:*' min-input` to have any effect.

Ah, you are right. I'll have to fix that. Thanks for reporting this.

**Comment by marlonrichert** [comment] 2020-10-31 22:25
@leoddd @wolfo I think I figured out what was causing these problems. I pushed in some changes that will hopefully fix them. Please `git pull` to update, restart your terminal and try again.

**Comment by marlonrichert** [comment] 2020-10-31 22:31
> Now it would only be nice if the unexpanded list also showed colors :-) Or maybe it's just me. But anyway, I know it's a very fresh feature, thank you for that.

@wolfo If you add the following line to your `~/.zshrc`, does that help?
```zsh
zstyle ':completion:*' group-name ''
```

**Comment by wolfo** [comment] 2020-11-01 00:59
> ```shell
> zstyle ':completion:*' group-name ''
> ```

Doesn't help with the colors in the unexpanded result list, unfortunately. It just separates results in the expanded list.

What I've noticed is that after the latest git pull, the unexpanded listing is restricted to 6 lines of results (plus hint header), instead of 9.

`zstyle ':autocomplete:list-choices:*' max-lines 100%` (200%, 10%) doesn't change that behavior.

**Comment by marlonrichert** [comment] 2020-11-01 09:11
> Doesn't help with the colors in the unexpanded result list, unfortunately. It just separates results in the expanded list.

Then you have another `zstyle` somewhere that’s overriding this. Are you using any Zsh framework, like Oh My Zh, Prezto or Zimfw?

**Comment by marlonrichert** [comment] 2020-11-01 09:12
> What I've noticed is that after the latest git pull, the unexpanded listing is restricted to 6 lines of results (plus hint header), instead of 9.

That might happen if your terminal has very few lines. Are you using `tmux`?

**Comment by marlonrichert** [comment] 2020-11-01 09:17
> zstyle ':autocomplete:list-choices:*' max-lines 100% (200%, 10%) doesn't change that behavior.

What happens if you try `zstyle ':autocomplete:*' max-lines 100%` instead?

**Comment by marlonrichert** [comment] 2020-11-01 12:03
@wolfo I pushed in another update. Please `git pull` and try again.

**Comment by wolfo** [comment] 2020-11-01 14:10
Mh, something now really clashes with something in my config after the last pull.

When typed while in ~
```
$ ls 
argument-rest  matches        r:|/=* r:|=*
```
When specifying "~/", even if it's already the working directory, it shows only files, not folders:
```
$ ls ~/
file:
BasiliskII_Prefs      include_antigen.zsh   qemu-monitor-socket= 
```
While for the Applications folder, it shows the invisible files and nothing else:
```
$ ls /Applications/
file:
.DS_Store   .localized
```

The above results probably won't happen with a less convoluted .zshrc, so maybe this is the wrong place to post it. I just noticed that weird behavior particularly since the latest commit 1da6623.

**Comment by wolfo** [comment] 2020-11-01 14:12
Anyway, when I use a very lean .zshrc with some color settings:
```
zstyle ':completion:*:processes' command 'ps -ax'
zstyle ':completion:*:processes-names' command 'ps -aeo comm='
zstyle ':completion:*' menu select
zstyle ':completion:*:builtins' list-colors '=*=1;38;5;142'
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:*:killall:*:processes-names' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:*:killall:*' menu yes select
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
autoload -Uz compinit
compinit

zmodload zsh/terminfo

source ~/.antigen/bundles/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
zstyle ':completion:*' tag-order '! history-words' '-'
zstyle ':autocomplete:*' min-input 3
zstyle ':autocomplete:*' max-lines 100%
```
and run it with `ZDOTDIR=/Users/wolfo/zshrc-test zsh`
The min-input and max-lines do have an effect now!

When the list would be longer - and gets shortened - it is still without colors. The complete list with colors returns with Control+Space, as before.

**Comment by marlonrichert** [comment] 2020-11-02 08:36
@wolfo Thanks, I'm able to reproduce it now. I'll investigate.

**Comment by marlonrichert** [comment] 2020-11-02 08:42
By the way: You don't need to run `compinit` yourself when using `zsh-autocomplete`. It already does it for you.

**Comment by balta2ar** [comment] 2020-11-02 13:46
I recently git pulled master and discovered that zsh-autocomplete has become significantly slower and less responsive. I tracked down the commits and it seems that it started at this commit: c6f9b91b658b7ae1d674d97f95bea2248cc6fdf1

**Comment by marlonrichert** [comment] 2020-11-02 16:23
@wolfo It should be fixed now.

**Closed by marlonrichert** 2020-11-02 16:23 UTC
Labels: Feature request
