### ISSUE TITLE
Prompt jumps up one line when on the last line

### ISSUE THREAD

**Issue by h0adp0re** [marlonrichert/zsh-autocomplete#260] opened 2021-05-18 09:37 UTC
* `zsh-autocomplete` version: 405c29211047968516c9dbd9f41146976725462e
* Zsh version: `zsh-5.8-0-g77d203f`
* Framework: none
* Plugin manager: none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
1. Fill the screen so the prompt is on the last line
2. Type any command or press return
3. The prompt jumps up one line (it's very fast with the steps above)

https://user-images.githubusercontent.com/11251772/118628851-ad661e80-b7d5-11eb-88ff-700f1e3641fe.mov

P.S. I love that you have used named directories for `zsh-autocomplete` _and_ that you're utilizing the `-C` flag for git. More plugin authors should know about these QOL improvements.

**Comment by marlonrichert** [comment] 2021-05-19 12:39
I cannot reproduce this. Which prompt theme do you use?

**Comment by h0adp0re** [comment] 2021-05-19 12:41
I use powerlevel10k. But it can be reproduced in the tmp folder with only `zsh-autocomplete` loaded.

**Comment by marlonrichert** [comment] 2021-05-19 12:59
Sorry, I still cannot reproduce this. I wonder if it's a bug in your terminal?

After doing `exec zsh -f`, what output do you get from `env`?

**Comment by h0adp0re** [comment] 2021-05-19 13:13
Haha, proof was the wrong word. Here's the stuff you wanted, stripped of compromising information. As is evident, I use tmux within alacritty. I could reproduce the same thing outside of tmux, as well as with Terminal.app.
```sh
ALACRITTY_LOG=/var/folders/6r/7k4l9vgs243_nf4nljm9sxm8v0y8kd/T/Alacritty-59174.log
COLORTERM=truecolor
COMMAND_MODE=unix2003
HOME=/var/folders/6r/7k4l9vgs243_nf4nljm9sxm8v0y8kd/T/tmp.Y6nHKj6d
LC_CTYPE=UTF-8
LOGNAME=h0adp0re
OLDPWD=/var/folders/6r/7k4l9vgs243_nf4nljm9sxm8v0y8kd/T/tmp.Y6nHKj6d
PATH=/usr/local/sbin:/Users/h0adp0re/.nvm/versions/node/v14.17.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/var/folders/6r/7k4l9vgs243_nf4nljm9sxm8v0y8kd/T/tmp.Y6nHKj6d
SHELL=/usr/local/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.LsKwrX6TMz/Listeners
TERM=screen-256color
TERM_PROGRAM=tmux
TERM_PROGRAM_VERSION=3.2
TMPDIR=/var/folders/6r/7k4l9vgs243_nf4nljm9sxm8v0y8kd/T/
TMUX=/private/tmp/tmux-906961485/default,59552,0
TMUX_PANE=%33
TMUX_PLUGIN_MANAGER_PATH=/Users/h0adp0re/.config/tmux/plugins/
USER=h0adp0re
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
__CFBundleIdentifier=io.alacritty
__CF_USER_TEXT_ENCODING=0x360F224D:0x0:0x2
P9K_TTY=old
_P9K_TTY=/dev/ttys003
LANG=en_US.UTF-8
DOTFILES=/Users/h0adp0re/.dotfiles
EDITOR=nvim
YSU_MESSAGE_FORMAT=💡 %alias = %command
YSU_MODE=BESTMATCH
HOMEBREW_NO_ANALYTICS=1
BAT_THEME=gruvbox-dark
FZF_COMPLETION_TRIGGER=~~
FZF_DEFAULT_OPTS=--color='prompt:#e78a4e,gutter:-1,pointer:#89b382,bg+:#45403d' --cycle --prompt='❯ ' --pointer='▶'
NNN_OPTS=dHS
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_mb=
LESS_TERMCAP_us=
LESS_TERMCAP_ue=
LESS_TERMCAP_so=
LESS_TERMCAP_se=
NVM_DIR=/Users/h0adp0re/.nvm
NVM_CD_FLAGS=-q
NVM_BIN=/Users/h0adp0re/.nvm/versions/node/v14.17.0/bin
NVM_INC=/Users/h0adp0re/.nvm/versions/node/v14.17.0/include/node
P9K_SSH=0
YSU_VERSION=1.7.3
_=/usr/bin/env
```

**Comment by marlonrichert** [comment] 2021-05-19 13:49
Aha, maybe the problem is `tmux`. Have you tried without?

**Comment by marlonrichert** [comment] 2021-05-20 17:37
As mentioned in the other issue, it looks like you're running Alacritty, but for some reason, your `$TERM` is set to `screen-256color `. Don't do that, unless you're actually using `screen`.

**Comment by h0adp0re** [comment] 2021-05-20 17:39
Where and how should I set my `TERM` then? I have it set to `xterm-256color` in my `alacritty.yml`:
```yml
env:
  TERM: xterm-256color
```
I know it's bad practice to set it inside your shell.

**Comment by marlonrichert** [comment] 2021-05-20 18:06
Never mind my comment. I was unaware of how `tmux` works exactly.

Anyway, closing this as per your request on #261.

**Closed by marlonrichert** 2021-05-20 18:06 UTC
Labels: bug, question
