### ISSUE TITLE
No autocomplete options when no command is typed

### ISSUE THREAD

**Issue by Dragonizedpizza** [marlonrichert/zsh-autocomplete#417] opened 2022-02-14 19:42 UTC
## Environment

```zsh
pc linux-gnu /usr/bin/zsh /bin/zsh zsh-5.8.1-0-g1a490c7
/home/arch/.znap/zsh-snap/functions/.znap.source:26
/home/arch/.znap/zsh-snap/functions/znap:42
/home/arch/.zshrc:16
```
* Operating system: Arch Linux 
* Terminal emulator: Konsole 

## Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

![image](https://user-images.githubusercontent.com/70718540/153934677-338bd542-be49-40a7-8892-0de3ead429bd.png)
(No autocomplete options, like directories I can go to)

**Comment by marlonrichert** [comment] 2022-02-20 15:11
@Dragonizedpizza @glotchimo Can you check whether this is a duplicate of #416?

**Comment by marlonrichert** [comment] 2022-02-20 16:43
Duplicate of #416.

**Closed by marlonrichert** 2022-02-20 16:43 UTC
Labels: bug, question
