### ISSUE TITLE
Frash install give error on cd command

### ISSUE THREAD

**Issue by remygrandin** [marlonrichert/zsh-autocomplete#242] opened 2021-04-14 09:32 UTC
* `zsh-autocomplete` version: 473d31a9c949a7e449a9b41fcd57b663c14f9216
* Zsh version: ubuntu/5.8-3ubuntu1
* Framework: Oh My Zsh
* Plugin manager:  none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cd /  # Do any cd command
chpwd_recent_filehandler:29: no such file or directory: /tmp/tmp.QU0P2N390o/.local/share/zsh/chpwd-recent-dirs #<== This error is unexpected
```

Basically each time I do a cd it error with 
```
chpwd_recent_filehandler:29: no such file or directory: /tmp/tmp.QU0P2N390o/.local/share/zsh/chpwd-recent-dirs
```

**Comment by marlonrichert** [comment] 2021-04-22 21:38
Duplicate of #244.

**Closed by marlonrichert** 2021-04-22 21:38 UTC
Labels: bug
