### ISSUE TITLE
Do not show "do you wish to see all X possibilities" unless tab is pressed

### ISSUE THREAD

**Issue by jerryc05** [marlonrichert/zsh-autocomplete#388] opened 2021-12-18 23:16 UTC
### Environment

```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```
```
apple darwin20.0 /bin/zsh /bin/zsh zsh-5.8-0-g77d203f
~/.local/share/zinit/zinit.git/zinit.zsh:1622
~/.local/share/zinit/zinit.git/zinit.zsh:1261
~/.local/share/zinit/zinit.git/zinit.zsh:2676
```

### Steps to reproduce
1. Type `pgrep ` (notice the space after `pgrep`).
2. Noticed that the terminal shows up `zsh: do you wish to see all 73 possibilities (75 lines)?`, which consumes the next char I pressed.
3. When I noticed that the first char is consumed, I pressed the backspace to delete all chars to the right of `pgrep`.
4. The prompt `zsh: do you wish to see all 73 possibilities (75 lines)?` shows up again

### Expected
If the terminal can hold all hints/expanded items/possibilities/etc., show them.
Otherwise, show as many as possible.
Please do not prompt `zsh: do you wish to see all 73 possibilities (75 lines)?`

**Comment by Altair-Bueno** [comment] 2022-01-05 16:40
You can disable it by adding this to your `.zshrc` config file

```zsh
zstyle ':completion:*' list-prompt   ''
zstyle ':completion:*' select-prompt ''
```
---

### `At Top: Hit TAB for more, or the character to insert`

The one i find more disturbing is `At Top: Hit TAB for more, or the character to insert`. It only appears when the terminal is small enough (or when there are a lots of options to choose from). It's the same behaviour: the terminal just keeps eating your characters and the only way im able to reset is to ^C and write the command anywhere else

![zsh on iTerm2](https://user-images.githubusercontent.com/67512202/148253492-7933ef18-8a70-4ec8-a9e7-f4f4e4aeccc3.png)

Does anyone know how to disable it? Google doesn't yield any good results.

#### Steps to reproduce

1. Reduce terminal size to somewhere around 50x10
2. type `git -`
3. Notice how zsh autocomplete just keeps eating your characters

**Comment by Altair-Bueno** [comment] 2022-01-06 20:41
Update: asiinema recording

https://asciinema.org/a/BluGyxHift2Wxkd9YTePMf1BV

**Comment by marlonrichert** [comment] 2022-01-11 15:35
> You can disable `do you wish..` by adding this to your `.zshrc` config file
> 
> ```zsh
> zstyle ':completion:*' list-prompt   ''
> zstyle ':completion:*' select-prompt ''
> ```

That's not a solution, though. It just leads to a different form of the same problem, which you yourself mentioned:

> The one i find more disturbing is `At Top: Hit TAB for more, or the character to insert`. It only appears when the terminal is small enough (or when there are a lots of options to choose from). It's the same behaviour: the terminal just keeps eating your characters and the only way im able to reset is to ^C and write the command anywhere else

This is a very tricky problem to solve and, unfortunately, I don't currently have time to solve it. Pull requests welcome! @jerryc05 @Altair-Bueno @JiajiaGuo

**Comment by Altair-Bueno** [comment] 2022-01-11 15:47
> very tricky problem to solve

Have any ideas where to start? Disabling the `zsh-autocomplete` plugin with both lines on my zshrc still shows the same message. I thought it was a zsh thing, not directly caused by your plugin

**Comment by marlonrichert** [comment] 2022-01-11 18:30
@Altair-Bueno Yes, it’s a Zsh thing, but it doesn’t matter in vanilla Zsh, because it’s not so bad if it appears only when you press Tab. The challenge for Zsh Autocomplete is to figure out how many completions will fit on screen _before_ they are passed to Zsh’s `compadd`, because once added, they cannot be removed.

**Comment by Omoeba** [comment] 2022-01-12 12:19
`zstyle ':completion:*:*:man:*:*' menu select=long search`fixes the man issue for me

**Comment by Altair-Bueno** [comment] 2022-01-12 12:55
> `zstyle ':completion:*:*:man:*:*' menu select=long search`fixes the man issue for me

It doesn't remove the message forever tho, but works better than my solution

> The challenge for Zsh Autocomplete is to figure out how many completions will fit on screen before they are passed to Zsh’s `compadd`, because once added, they cannot be removed

I'm not familiar with zsh enough to work on this, but I'll give it a try

**Comment by Altair-Bueno** [comment] 2022-03-25 10:36
I searched zsh's documentation looking for an easy solution like a setting but i couldn't found anything useful. I settle with a `120x38` terminal and [Omoeba's solution](https://github.com/marlonrichert/zsh-autocomplete/issues/388#issuecomment-1010988568). It is not perfect but works great 99% of the time

**Comment by RyanzpLee** [comment] 2022-03-25 16:10
Interesting as when I use a 122x90 terminal with that zstyle 'fix', it still shows up the prompt issue.

**Comment by Altair-Bueno** [comment] 2022-03-26 19:17
Another easy solution is disabling that specific completion that is troublesome. You can either remove entirety the function file or part of it. Note that this will disable completions for that specific command/argument entirety. This might be unacceptable tho, but is the only thing i can think of

You can find completion functions are defined inside scripts located on `$FPATH`'s folders

**Comment by marlonrichert** [comment] 2022-03-31 14:06
> Another easy solution is disabling that specific completion that is troublesome. 

That actually is a good idea. I could implement a `zstyle` mechanism in Zsh Autocomplete with which you can disabled autocompletion for specific commands.

**Comment by marlonrichert** [comment] 2022-03-31 14:39
@Altair-Bueno @RyanzpLee @Omoeba @jerryc05 I'm unable to reproduce the test cases given in this issue anymore. I think d6a0ff574679280af52258ee6d2dcd3857283270 might have fixed the bug. Can someone confirm?

**Comment by Altair-Bueno** [comment] 2022-03-31 19:00
> @Altair-Bueno @RyanzpLee @Omoeba @jerryc05 I'm unable to reproduce the test cases given in this issue anymore. I think [d6a0ff5](https://github.com/marlonrichert/zsh-autocomplete/commit/d6a0ff574679280af52258ee6d2dcd3857283270) might have fixed the bug. Can someone confirm?


It's working great for me!! I can reduce the terminal size to an absurd size with no problems

<img width="347" alt="image" src="https://user-images.githubusercontent.com/67512202/161129273-65d44350-125b-4703-bb2e-b7b83b03c41b.png">

#### Environment

```yaml
zsh: zsh 5.8 (x86_64-apple-darwin21.0)
terminal: iTerm2 3.4.15
.zshrc: |
	zstyle ':completion:*:*:man:*:*' menu select=long search
```

**Comment by RyanzpLee** [comment] 2022-03-31 22:43
Still not working for me @marlonrichert  even with a full screen terminal on 13 inch macbook pro (macos Montery v12.3). Do you have any additional settings in your zshrc @Altair-Bueno ? That's amazing that it's working for you though. I currently have it installed through oh my zsh method, but I also just tried doing it the manual install method.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/69594457/161160578-145b910c-250e-4e84-ad68-4bb98115ba82.png">
<img width="498" alt="image" src="https://user-images.githubusercontent.com/69594457/161160590-a302073e-2cd5-4bde-877e-8aa8091f989b.png">




```
zsh: zsh 5.8 (x86_64-apple-darwin21.0)
oh-my-zsh: version 53863e7
terminal: kitty (Version 0.24.4) && iTerm2 3.4.15
.zshrc: ...  zstyle ':completion:*:*:man:*:*' menu select=long search
```

**Comment by tshu-w** [comment] 2022-04-01 02:43
works great for me too.

**Comment by Altair-Bueno** [comment] 2022-04-01 09:03
Sure @RyanzpLee! You can check my zsh config on my [dotfile repository](https://github.com/Altair-Bueno/Demeter)

- [zshenv](https://github.com/Altair-Bueno/Demeter/blob/master/backup/.zshenv)
- [zshrc](https://github.com/Altair-Bueno/Demeter/blob/master/backup/.zshrc)

I think most config options are well documented, but don't hesitate to ask if you have any questions



PS: Zoxide works on my machine

<img width="482" alt="image" src="https://user-images.githubusercontent.com/67512202/161231449-b027a5dc-877f-4fa8-80a2-912837983576.png">

PS2: Did you try changing your theme to a single line prompt like mine? Maybe zsh-autocomplete expects one single line prompts

**Comment by marlonrichert** [comment] 2022-04-01 10:27
@RyanzpLee Is that only for your `z` command or are you seeing that elsewhere, too? Which `z` command do you use?

**Comment by marlonrichert** [comment] 2022-04-01 10:29
> I can still reproduce the issue with both `pgrep` and `man`.

@Omoeba I cannot reproduce it with `pgrep`, but I can indeed reproduce it with `man`. Thanks, I'll have a look at it.

**Comment by RyanzpLee** [comment] 2022-04-01 10:48
Thanks @Altair-Bueno I'll check it out and see what works. And I did indeed try a bare bones .zshrc config with only the zsh autocomplete plugin sourced but I still got the error.

@marlonrichert  I'm using Z jumper and it comes with oh my zsh. I've added it to my plugins list and here's my config file too [Zshrc](https://github.com/RyanzpLee/dotfiles/blob/main/zshrc)

**Comment by marlonrichert** [comment] 2022-04-01 11:03
@RyanzpLee After you get `zsh: do you wish to see all 121 possibilities (61 lines)?`, can you please press `y` and paste the output here?

**Comment by RyanzpLee** [comment] 2022-04-01 12:13
@marlonrichert  I've attached the output (but have removed a few directories)
```shell
1/
/Applications
/Applications/kitty.app
/System/Volumes/Data/home
/Users
$HOME/.config
$HOME/.config/coc
$HOME/.config/kitty
$HOME/.config/nvim
$HOME/.config/nvim/lua
$HOME/.fzf
$HOME/.iterm2
$HOME/.local
$HOME/.local/share
$HOME/.local/share/nvim
$HOME/.local/share/nvim/plugged/coc.nvim
$HOME/.local/share/nvim/site/autoload
$HOME/.local/share/nvim/site/pack/packer/start
$HOME/.oh-my-zsh
$HOME/.oh-my-zsh/cache
$HOME/.oh-my-zsh/cache/completions
$HOME/.oh-my-zsh/custom
$HOME/.oh-my-zsh/custom/plugins
$HOME/.oh-my-zsh/custom/plugins/example
$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
$HOME/.oh-my-zsh/custom/themes
$HOME/.oh-my-zsh/custom/themes/powerlevel10k
$HOME/.oh-my-zsh/plugins
$HOME/.oh-my-zsh/themes
$HOME/.oh-my-zsh/tools
$HOME/.tmux
$HOME/.tmux/plugins
$HOME/.tmux/plugins/tpm
$HOME/.im
$HOME/Applications
$HOME/Desktop
$HOME/Documents
$HOME/Documents/keyboards
$HOME/Downloads
$HOME/Downloads/kitty-master
$HOME/GraphQLProjects/odyssey-lift-off-part2/server
$HOME/GraphQLProjects/odyssey-lift-off-part3
$HOME/GraphQLProjects/odyssey-lift-off-part3/server
$HOME/GraphQLProjects/odyssey-lift-off-part3/server/src
$HOME/Library
$HOME/Library/Application\ Support
$HOME/Library/Application\ Support/Code/logs
$HOME/Library/Application\ Support/Google/Chrome
$HOME/Library/Application\ Support/Google/Chrome/Profile\ 1
$HOME/Library/Keyboard
$HOME/Library/Keyboard/en-dynamic.lm
$HOME/bin
$HOME/copilot\ test
$HOME/digital-automation-tools
$HOME/dotfiles
$HOME/dotfiles/kitty
$HOME/dotfiles/nvim
$HOME/dotfiles/nvim/lua/user
$HOME/dotfiles/tmux
$HOME/dotfiles/tmux/plugins
$HOME/dotfiles/tmux/plugins/tpm
$HOME/dotfiles/tmux/plugins/tpm/scripts
$HOME/fzf
$HOME/git-clones
$HOME/git-clones/zsh-autocomplete
$HOME/lspTest
$HOME/webpack-test
$HOME/webpack-test/test
$HOME/webpack-test/test/node_modules
$HOME/webpack-test/test/src
$HOME/zsh
/bin
/private/etc
/usr
/usr/bin
/usr/local/Cellar/fzf/0.29.0
```

**Comment by marlonrichert** [comment] 2022-04-11 09:46
@RyanzpLee `z` completion uses Zsh’s old, deprecated [`compctl` completion](https://zsh.sourceforge.io/Doc/Release/Completion-Using-compctl.html) under the hood. Zsh Autocomplete currently does not support that, but it will be fixed by implementing #426.

**Comment by RyanzpLee** [comment] 2022-04-11 10:08
Ok @marlonrichert  thanks for letting me know. I'll try using zoxide which seems to work well with zshautocomplete!

**Closed** 2022-05-05 13:58 UTC
Labels: bug, question

**Comment by marlonrichert** [comment] 2022-05-05 13:59
@jerryc05 @Omoeba @Altair-Bueno @RyanzpLee @Altair-Bueno @tshu-w @JiajiaGuo It should all be fixed now.

**Comment by Omoeba** [comment] 2022-05-05 20:12
> @jerryc05 @Omoeba @Altair-Bueno @RyanzpLee @Altair-Bueno @tshu-w @JiajiaGuo
> 
> It should all be fixed now.

`pgrep` is fixed but the issue still remains for `man`.
```
❯ man
zsh: do you wish to see all 312 possibilities (65 lines)?
```

**Comment by marlonrichert** [comment] 2022-05-06 05:18
@Omoeba I’ve tested with `man` and it works fine for me. Can you give me exact circumstances under which this happens?

**Comment by Omoeba** [comment] 2022-05-06 20:40
> @Omoeba I’ve tested with `man` and it works fine for me. Can you give me exact circumstances under which this happens?

I typed `man ` after running the following commands.
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
However, after repeated testing, I noticed that the issue only starts to occur after a some time. The only way to temporarily "resolve" it is by running `rm ~/.cache/zsh/compdump`.

**Comment by marlonrichert** [comment] 2022-05-11 13:28
@Omoeba Sorry, I'm still unable to reproduce it. Should you find a way to create a reliable test case for it, then please open a new issue for it.

**Comment by Omoeba** [comment] 2022-07-18 08:36
@marlonrichert I've done some additional testing and the way to "fix" the issue is by printing 10 newlines at the start of each session, such as by putting `echo -e '\n\n\n\n\n\n\n\n\n\n'` at the end of your `~/.zshrc`. I've also tried fiddling around with `zstyle ':autocomplete:*' list-lines` to no avail.
