### ISSUE TITLE
History is ordered by reverse alphanumerical instead of reverse numerical

### ISSUE THREAD

**Issue by maarekj** [marlonrichert/zsh-autocomplete#254] opened 2021-05-14 12:36 UTC
* `zsh-autocomplete` version: 966312b149fb82a9d01144454de886b6a626ce69
* Zsh version: ubuntu/5.8-3ubuntu1
* Framework: none
* Plugin manager: none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% echo "1"
% echo "2"
% echo "3"
% echo "4"
% echo "5"
% echo "6"
% echo "7"
% echo "8"
% echo "9"
% echo "10"
% echo "11"
% echo "12"
% # press up key
10 echo 9
11 echo 10
12 echo 11
 1 source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
 2 echo 1
 3 echo 2
 4 echo 3
 5 echo 4
 6 echo 5
 7 echo 6
 8 echo 7
 9 echo 8
```

Hello,

there is bug here. The history must be reverse ordered by numerical line of history file. But here, the history is ordered by reverse alphanumerical. Then the `line 12` whose is the last line appears before the `line 9`.

![Capture d’écran de 2021-05-14 14-30-56](https://user-images.githubusercontent.com/1654977/118271484-9ff12180-b4c1-11eb-803c-0c5f199645fe.png)

Thanks you for your work.

**Comment by marlonrichert** [comment] 2021-05-14 13:16
> * `zsh-autocomplete` version: git -C ~zsh-autocomplete rev-parse @
> * Zsh version: print $ZSH_PATCHLEVEL

Can you please fill in which `zsh-autocomplete` and Zsh versions you are using?

Also, I'm unable to reproduce this with the steps you've given.

**Comment by maarekj** [comment] 2021-05-14 15:17
I update my first comment with version of zsh-autocomplete and zsh version

**Comment by maarekj** [comment] 2021-05-14 15:19
I seem to have followed the steps to the letter.
I will try again in a few days.

**Comment by maarekj** [comment] 2021-05-19 10:13
See my step on an asciinema rec:
https://asciinema.org/a/FwyEmHiSKmyf4cHWUUZtxlRPv

**Comment by maarekj** [comment] 2021-05-19 13:25
```shell
> HOME=$PWD exec zsh -f
maarek-xps% env
LC_TELEPHONE=fr_FR.UTF-8
GDMSESSION=ubuntu
GJS_DEBUG_OUTPUT=stderr
DESKTOP_SESSION=ubuntu
PWD=/tmp/tmp.A8hEtmzoby
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=maarek
HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
INFOPATH=/home/linuxbrew/.linuxbrew/share/info:/home/linuxbrew/.linuxbrew/share/info:/home/linuxbrew/.linuxbrew/share/info:
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_MEASUREMENT=fr_FR.UTF-8
XDG_SESSION_TYPE=x11
PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/maarek/.tmuxifier/bin:/home/maarek/.yarn/bin:/tmp/fnm_multishell_135419_1621430544580/bin:/home/maarek/.fnm:/home/maarek/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/maarek/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/maarek/.config/composer/vendor/bin:/home/maarek/.zsh/fzf/bin
HOME=/tmp/tmp.A8hEtmzoby
USERNAME=maarek
QT_IM_MODULE=ibus
USER=maarek
DISPLAY=:1
INVOCATION_ID=49fde8cf5d0a46ceb10e0332ff2a1b9d
JOURNAL_STREAM=8:63247
HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
LC_NAME=fr_FR.UTF-8
LANG=fr_FR.UTF-8
XAUTHORITY=/run/user/1000/gdm/Xauthority
LC_PAPER=fr_FR.UTF-8
HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
SHLVL=1
SESSION_MANAGER=local/maarek-xps:@/tmp/.ICE-unix/3729,unix/maarek-xps:/tmp/.ICE-unix/3729
IM_CONFIG_PHASE=1
XDG_RUNTIME_DIR=/run/user/1000
SSH_AGENT_PID=3687
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=ubuntu
VTE_VERSION=6003
XDG_CURRENT_DESKTOP=ubuntu:GNOME
LIBVIRT_DEFAULT_URI=qemu:///system
GNOME_TERMINAL_SERVICE=:1.883
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
_=/usr/bin/env
LC_ADDRESS=fr_FR.UTF-8
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
SHELL=/usr/bin/zsh
XDG_SESSION_CLASS=user
LC_IDENTIFICATION=fr_FR.UTF-8
MANAGERPID=3438
PAPERSIZE=a4
XMODIFIERS=@im=ibus
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GTK_MODULES=gail:atk-bridge
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/72070bea_184e_4670_931b_bc0b3c74af59
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
LC_NUMERIC=fr_FR.UTF-8
GNOME_SHELL_SESSION_MODE=ubuntu
TERM=xterm-256color
XDG_MENU_PREFIX=gnome-
COLORTERM=truecolor
LC_TIME=fr_FR.UTF-8
MANPATH=/home/linuxbrew/.linuxbrew/share/man:/home/linuxbrew/.linuxbrew/share/man:/home/linuxbrew/.linuxbrew/share/man:::
WINDOWPATH=2
QT_ACCESSIBILITY=1
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
LC_MONETARY=fr_FR.UTF-8
OLDPWD=/tmp/tmp.A8hEtmzoby
ZSH=/home/maarek/.oh-my-zsh
EDITOR=code
FZF_BASE=/home/maarek/.zsh/fzf
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
P9K_SSH=0
FNM_MULTISHELL_PATH=/tmp/fnm_multishell_135419_1621430544580
FNM_DIR=/home/maarek/.fnm
FNM_LOGLEVEL=info
FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
TMUXIFIER=/home/maarek/.tmuxifier
P9K_TTY=old
_P9K_TTY=/dev/pts/5
```

**Comment by maarekj** [comment] 2021-05-19 13:47
The bug occurs from the version 966312b149fb82a9d01144454de886b6a626ce69
At the version 1b0e714f0b96afe28019e738c5941fbce60fc058 and before all is ok

**Comment by marlonrichert** [comment] 2021-05-20 11:59
> In a freshly installed ubuntu container (via docker), the bug is not present.

That’s interesting.

If you `unset` all your `LC_*` and `LANG` vars, does the bug persist?

What output do you get from the following?
```zsh
% typeset -a tmp=()
% printf -v tmp '%2.2s' {15..5}
% print ${(@nq+)tmp}
% _autocomplete.sort_by_length ${(@nq+)tmp}; print $reply
```
Is it the same with and without your `LC_*` vars?

**Comment by maarekj** [comment] 2021-05-20 12:27
```zsh
> typeset -a tmp=()
> printf -v tmp '%2.2s' {15..5}
> print ${(@nq+)tmp}
# 10 11 12 13 14 15 ' 5' ' 6' ' 7' ' 8' ' 9'
> _autocomplete.sort_by_length ${(@nq+)tmp}; print $reply
# 10 11 12 13 14 15 ' 5' ' 6' ' 7' ' 8' ' 9'
```
```zsh
> unset LC_ADDRESS LC_IDENTIFICATION LC_MEASUREMENT LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_TIME LANG
> printf -v tmp '%2.2s' {15..5}
> print ${(@nq+)tmp}
# 10 11 12 13 14 15 ' 5' ' 6' ' 7' ' 8' ' 9'
> _autocomplete.sort_by_length ${(@nq+)tmp}; print $reply
# 10 11 12 13 14 15 ' 5' ' 6' ' 7' ' 8' ' 9'
```

**Comment by maarekj** [comment] 2021-05-21 10:12
Which function bug in zsh ?
Please, you can give me some informations on the bug that I should submit to zsh mailing list ?

**Comment by maarekj** [comment] 2021-05-21 10:44
In the documentation of zsh, I see in section [14.3.1: Parameter Expansion Flags](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Command-Substitution):


> **n**
> Sort decimal integers numerically; if the first differing characters of two test strings are not digits, **sorting is lexical**. Integers with more initial zeroes are sorted before those with fewer or none. Hence the array ‘foo1 foo02 foo2 foo3 foo20 foo23’ is sorted into the order shown. May be combined with ‘i’ or ‘O’.


So this seems to be the normal behavior.

## Suggestions
If we replace `${(@nq+)tmp}` by `${(@nq+)tmp/ /0}` it works

**Comment by marlonrichert** [comment] 2021-05-21 17:42
Thanks for spotting that. I will fix it.

**Comment by marlonrichert** [comment] 2021-05-22 18:37
Should be fixed now.

**Closed by marlonrichert** 2021-05-22 18:37 UTC
Labels: bug

**Comment by maarekj** [comment] 2021-05-24 07:49
**Thank you** very much, it's work !
