### ISSUE TITLE
I doesnt`t work

### ISSUE THREAD

**Issue by 1Spinne** [marlonrichert/zsh-autocomplete#372] opened 2021-11-22 20:40 UTC
When I start the plugin, my zsh crashes
### Environment
zsh: no such user or named directory: zsh-autocomplete

### Steps to reproduce
It doesn't work in this shell only in the default.
The default shell just crashes without any error, when I run `znap source marlonrichert/zsh-autocomplete`

**Comment by 1Spinne** [comment] 2021-11-22 20:42
I installed it with znap

**Comment by marlonrichert** [comment] 2021-11-22 20:52
Closing this as not reproducible. I'll reopen it if you can provide me with a minimal, reproducible test case. If I cannot reproduce your problem, then I cannot fix it.

**Closed by marlonrichert** 2021-11-22 20:52 UTC
Labels: bug
