### ISSUE TITLE
.autocomplete.recent_paths.add:shift:16: shift count must be <= $#

### ISSUE THREAD

**Issue by blueray453** [marlonrichert/zsh-autocomplete#463] opened 2022-08-06 07:21 UTC
- [x] I have carefully read all of the instructions in this issue template.
- [ ] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
$ print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1

ubuntu linux-gnu /usr/bin/zsh /usr/bin/zsh ubuntu/5.8-3ubuntu1.1
/home/ismail/.zshrc:1
d8bfbef (grafted, HEAD -> main, origin/main, origin/HEAD) Improve `ignored-input` documentation
```

* Zorin OS 16
* Terminal emulator: Alacritty

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [ ] I have copy-pasted my entire test session into the same code block.

Terminal close abruptly. I could not reproduce it. But in log files in `$HOME/.local/share/zsh-autocomplete/log` the error is:

```
.autocomplete.recent_paths.add:shift:16: shift count must be <= $#
.autocomplete.recent_paths.add:shift:16: shift count must be <= $#
.autocomplete.recent_paths.add:shift:16: shift count must be <= $#
.autocomplete.recent_paths.add:shift:16: shift count must be <= $#
```
I did a little research. 

https://stackoverflow.com/questions/71567420/how-to-handle-error-shift-count-must-be-in-zsh

I think a little check in `_autocomplete.recent_paths` will be enough.

**Comment by marlonrichert** [comment] 2022-08-06 12:23
Duplicate of #441.

**Closed by marlonrichert** 2022-08-06 12:23 UTC
Labels: bug
