### ISSUE TITLE
zsh-autocomplete seems to freeze when completing sourcing of folder, does not show subfolders

### ISSUE THREAD

**Issue by andreasWallner** [marlonrichert/zsh-autocomplete#427] opened 2022-04-01 10:00 UTC
If I try to use tab-completion when sourcing from a folder (in my case a python virtualenv) .
When trying to complete the dotfolder or subfolders completion takes ~30 seconds and seems to fail to me (see examples below).
The issue only occurs when trying to complete when sourcing from the folder (via `. folder/...` or `source .folder/...`), the issue does not occur when e.g. cd'ing into it.

## Environment

```zsh
% print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
ubuntu linux-gnu /bin/zsh -zsh ubuntu/5.8-3ubuntu1.1
% print -l $_autocomplete__funcfiletrace
/home/wallnean/.config/zsh/zsh-snap/functions/.znap.source:26
/home/wallnean/.config/zsh/zsh-snap/functions/znap:42
/home/wallnean/.zshrc:3
% git -C ~zsh-autocomplete log --oneline -n1
7ab87cb (grafted, HEAD -> main, origin/main, origin/HEAD) Remove the Zsh version checks
```
* Operating system: Ubuntu 20.04 in WSL2
* Terminal emulator: Windows Terminal 1.8.1521.0

## Steps to reproduce

```zsh
myhost 1 ~% cd $(mktemp -d)
myhost 1 /tmp/tmp.FWiG4o1dDT% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 0), reused 25 (delta 0), pack-reused 0
Unpacking objects: 100% (59/59), 1.64 MiB | 2.70 MiB/s, done.
myhost 1 /tmp/tmp.FWiG4o1dDT% > .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
myhost 1 /tmp/tmp.FWiG4o1dDT% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% mkdir foo
% touch foo/blub
% mkdir foo/sub
% . f # press tab here, wait for seconds until bell, no completion occurs, shows many executables starting with f - would expect completion to '. foo/'
file
FCoEMsg.dll*              FDResPub.dll*                                                           FM20.DLL*                     FM20ENU.DLL*                 FMAPO64.dll*              FM_Speech_PP64.dll*
FNTCACHE.DAT*             FSDeployRes.dll*                                                        FTLang.dll*                   FWPUCLNT.DLL*                FXSAPI.dll*               FXSCOM.dll*
FXSCOMEX.dll*             FXSCOMPOSE.dll*                                                         FXSCOMPOSERES.dll*            FXSCOVER.exe*                FXSEVENT.dll*             FXSMON.dll*
% . foo # press tab here, same issue occurs - would expect completion to '. foo/'
file
BootMenuUX.dll*   boot.sdi*     bootcfg.exe*             bootctl*          bootim.exe*   bootloadHID*   bootsect.exe*  bootstat.dat*  bootstr.dll*  bootux.dll*  fcon.dll*     flock*                     fodhelper.exe*    fold*
fontdrvhost.exe*  fontext.dll*  fontgroupsoverride.dll*  fontmanager.dll*  fontsub.dll*  fontview.exe*  forfiles.exe*  format.com*    from@         look*        rootlesskit*  rootlesskit-docker-proxy*  rootporterr.mof*
all matches
BootMenuUX.dll boot.sdi bootcfg.exe bootctl bootim.exe bootloadHID bootsect.exe bootstat.dat bootstr.dll bootux.dll fcon.dll flock fodhelper.exe fold fontdrvhost.exe fontext.dll fontgroupsoverride.dll fontmanager.dll fontsub.dll font...
% . foo/ # press tab here, completes to '. foo/blub' - would expect a selection for either blub or sub
file
blub
% . foo/s #press tab here, completes to '. foo/blub' - would expect completion to '. foo/sub'
file
blub
% . foo # press tab here, wait a few seconds, press ctrl+c
Killed by signal in _path_files after 9s
```

**Comment by marlonrichert** [comment] 2022-04-01 11:09
I'm unable to reproduce this with the steps you've given. However, it looks like you're on WSL, to which I don't have access. Perhaps the problem is specific to that setup?

Can you try the same config in a Zsh that's not running on WSL?

**Comment by andreasWallner** [comment] 2022-04-01 13:47
Sure, once I'm home I can try on my native linux machine.

**Comment by andreasWallner** [comment] 2022-04-01 13:53
I remembered that I do have a Ubuntu VM as well, tried it there.
While the slowdown seems to be a WSL issue (possibly caused by the folders searched for possible completions?) it does still complete unexpected values.
```
% . f # tab -> completes to '. factor', expected would be '. foo'
% . foo # tab -> completes to '. foo2ddst'
% . foo/s # tab -> completes to '. foo/blub'
```

**Comment by marlonrichert** [comment] 2022-04-11 13:11
> ```
> % . f # tab -> completes to '. factor', expected would be '. foo'
> ```

Why/how would `. f` be expected to complete to `. foo`? Can you provide an isolated test case with which I can reproduce the problem?

**Comment by andreasWallner** [comment] 2022-04-12 16:18
I'd expect the completion because of the `foo` folder that we created just before, here a single repro:
```
hostname 1 /tmp% cd $(mktemp -d)
hostname 1 /tmp/tmp.juRl68Wclr% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 0), reused 25 (delta 0), pack-reused 0
Unpacking objects: 100% (59/59), 1.64 MiB | 723.00 KiB/s, done.
hostname 1 /tmp/tmp.juRl68Wclr% > .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
hostname 1 /tmp/tmp.juRl68Wclr% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% mkdir foo
% . f
```

**Comment by marlonrichert** [comment] 2022-04-14 06:54
Ah, I see. Sorry, I got a bit confused there. Yes, I can reproduce that. I'll see what I can do about it.

**Comment by marlonrichert** [comment] 2022-04-14 07:36
It's expected behavior, because [`file` won't look for files in the current dir](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#index-_002e), unless the specified path contains a `.`:
> <dl>
> <dt><tt>.</tt> <var>file</var> [ <var>arg</var> ... ]</dt>
> <dd><p>Read commands from <var>file</var> and execute them in the current shell
> environment.
> </p>
> <p>If <var>file</var> does not contain a slash, or if <tt>PATH_DIRS</tt> is set,
> the shell looks in the components of <tt>$path</tt> to find the directory
> containing <var>file</var>.  Files in the current directory are not read
> unless ‘<tt>.</tt>’ appears somewhere in <tt>$path</tt>. [...]
> </dd>
> </dl>

If you want to get completions for files and dirs in the current dir, then you will need to first type `. ./`.

In any case, completion for `.` is handled by the `_source` function that ships with Zsh and out of scope for the Zsh Autocomplete plugin. If you would like it to behave differently, please write to the [`zsh-workers` mailing list](https://zsh.sourceforge.io/Arc/mlist.html).

**Closed by marlonrichert** 2022-04-14 07:36 UTC
Labels: bug

**Comment by andreasWallner** [comment] 2022-04-15 08:35
Thanks for looking into it!
